### ISSUE TITLE
Use infrared proximity sensor to transmit some barcode types

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#12]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [brarcher](https://github.com/brarcher)**
_Saturday Jun 10, 2017 at 02:52 GMT_
_Originally opened as https://github.com/brarcher/loyalty-card-locker/issues/101_

----

The Beep and Go app (now [discontinued](http://mobeam.com/)) used the infrared proximity sensor to pulse patterns that tricked barcode readers into reading a barcode ([link](https://techcrunch.com/2013/03/14/samsung-taps-mobeam-to-bring-beamable-barcodes-to-the-galaxy-s4-could-wallet-integration-be-next/)). 

Determine if something similar can be done for this application to help linear barcodes be better read by scanners which cannot scan screens.

**Comment by TheLastProject** [comment]
This is something someone else will have to pick up, as there are no places nearby me at all that scan like this.

**Comment by Efreak** [comment]
They may be taking about standard barcode readers like are used at the supermarket and other retail; *linear barcode reader* to me sounds like the [old style wand](https://www.barcodesinc.com/cats/barcode-scanners/wand.htm), but reading the article that seems wrong.

**Comment by TheLastProject** [comment]
I understood what was meant, but I don't have any place where I could test anything like this. All stores I ever go to scan just fine with showing a QR code on the screen. That's what I meant with needing someone else to pick it up.

**Comment by TheLastProject** [comment]
Going to close this because this issue is best solved by ignoring it. This is clearly the old style of doing things, and these old style barcode readers will likely be replaced at companies as they break. So slowly but surely, this probably is going to solve itself. Besides that, phones with infrared blasters are very rare nowadays.

**Comment by Efreak** [comment]
> Besides that, phones with infrared blasters are very rare nowadays.

Unfortunately. It's on my wishlist for my actually buying a premium phone. Along having dual sim *and* microsd, nfc, and qi charging. Lacking a headphone jack means I can't even use a third party ir blaster anymore.
