### ISSUE TITLE
Adding a card to a group in a smartly way

### ISSUE THREAD

**Issue by FinixFighter** [TheLastProject/Catima#129]
Hi! I think it would be very useful to be able to add a card to a certain group just by long pressing on a card and then clicking on a label saying "Add to", then you can select (for example from a list) in which group you would like to add that card. For example, suppose you added a new card called "Chicken for all" in the default section; then you create a group called "Restaurants". If you want "Chicken for all" in the "Restaurants" group, now you have to add it again in the new group. It would be extremely useful to be able to long press on that card and clicking "Add to group:". Actually, by long pressing on card, you only get "Share" and "Copy ID to clipboard".

**Comment by lgasp** [comment]
This enanchement would be very useful. There is no way to move cards between groups, as it  is now

**Comment by Unreal-Dreams** [comment]
@TheLastProject  Can you suggest what kind of UI changes are you excepting. Do we add a drop-down menu in the header on long click or some other method?

**Comment by TheLastProject** [comment]
Hmm, I think this may not be the most logical way to go for it anymore, given the system was so changed.

May make most sense to in the group management screen add an extra button that gives you a list of all your cards with a checkbox if they are in that group so that you can in one go change every card in that group.

So you start Catima, go to Manage Groups, click a button on a group and you get a "Select all cards that should be part of this group" with a checkbox next to each card and when you press OK it updates every card.

**Comment by Kajal13081** [comment]
Hey, @TheLastProject  I want to solve this issue. Could you please explain this issue a bit, like the process how to approach to this issue?

**Comment by TheLastProject** [comment]
I think the best way is to add a button to each group in ManageGroupsActivity that gives you a dialog with all cards.

This dialog should have a checkbox in front of each card which is checked if the card is in the group and unchecked if it is not.

When pressing OK, it should update the group list of all changed cards depending on the checkbox in front of each card.

**Comment by Kajal13081** [comment]
> I think the best way is to add a button to each group in ManageGroupsActivity that gives you a dialog with all cards.
> 
> This dialog should have a checkbox in front of each card which is checked if the card is in the group and unchecked if it is not.
> 
> When pressing OK, it should update the group list of all changed cards depending on the checkbox in front of each card.

Okay. So I would like to work on this. Can you assign me this issue?

**Comment by TheLastProject** [comment]
Assigned, have fun! :)

**Comment by TheLastProject** [comment]
Hey @Kajal13081, I haven't heard from you on this for a while. If you still want to work on this, please tell me. Otherwise I will free this up for someone else to work on.

**Comment by TheLastProject** [comment]
Forgot to close this, #557 fixed this by adding an edit button for each group in the groups list where you can choose exactly which cards should be in it
