### ISSUE TITLE
Advanced sorting UI

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#140]
Probably a left side sidebar with the following options:

Sort:
- Alphabetically
- Expiry date
[Sort ascending/descending]

Show groups:
- All groups
- [Option for each group]
- [Create new group]

**Comment by jovandeginste** [comment]
Could you track how often a card is opened, and offer a sort by that metric? I would really love it to have my often-used cards on top...

**Comment by jovandeginste** [comment]
Alternative might be to have the possibility to mark cards as "favorites", and show them on top sorted by whatever other sorting is selected

**Comment by TheLastProject** [comment]
>Could you track how often a card is opened, and offer a sort by that metric? I would really love it to have my often-used cards on top...

Oh that is pretty clever. Would make sense to store timestamps so we can check which one was most commonly used in the past 30 days or so and prioritize that way.

>Alternative might be to have the possibility to mark cards as "favorites", and show them on top sorted by whatever other sorting is selected

This already exists though, just press the star icon in the top right when viewing a card. Favourites will always be on top.

**Comment by jovandeginste** [comment]
> This already exists though, just press the star icon in the top right when viewing a card. Favourites will always be on top.

Is this a feature from catima, or was this already in the original app? I never saw this, but it's exactly what I meant.... 😳

**Comment by TheLastProject** [comment]
It's a community-contributed feature that didn't make it into Loyalty Card Keychain before the developer stopped working on it: https://github.com/TheLastProject/Catima/pull/70 :)

**Comment by jovandeginste** [comment]
Okay, that explains! Thanks for pointing it out!

**Comment by TheLastProject** [comment]
Closing as a duplicate of #7 because I actually want to implement it in a simpler way.
