### ISSUE TITLE
Import from Fidme

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#168]
Fidme allows users to export their data by going to profile -> Data protection -> Extract my data. This sends a .zip file to the user's email address.

This zip file contains the following files:

`user_profile.csv`: User profile information (useless to Catima)
`tickets.csv`: Not quite sure what this is
`loyalty_stamps.csv`: Not quite sure what this is either
`loyalty_stamp_rewards.csv`: Again, not quite sure
`loyalty_programs.csv`: The loyalty cards the user has in a simple to parse CSV file
`loyalty_points.csv`: Not quite sure

So, we can support importing from this zip file by:
1. Allowing the user to select it
2. Unzip it
3. Parse the loyalty_programs.csv file

@mgohin: Would you be willing to test this feature when it is ready?

**Comment by mgohin** [comment]
O.M.G that's reactivity !
Of course I'll test it 👍

**Comment by mgohin** [comment]
do you have any idea when it'll be available on the android app ?

**Comment by TheLastProject** [comment]
I'm hoping to have a first prototype of this import available today or tomorrow, otherwise it'll be by the end of the week probably.

**Comment by mgohin** [comment]
Nice 👍
I'll wait until I have the import option and test it.

I'm ok to wipe app data (camino) and test until it's ok

**Comment by TheLastProject** [comment]
I implemented it in b9e152e3c4308178f6e2e933f72c2dd9f41d93e7 but I am a bit unsure about the notes the app allows you to add to your cards. Could you look into the ZIP file a Fidme export gives you? My test `loyalty_programs.csv` gave me the following:
```
Retailer;Program;Added At;Reference;Firstname;Lastname
Albert Heijn;Bonus Kaart;2021-03-24 16:47:47 UTC;123435363634;;
```

Anyway, I've attached a debug APK in the zip file below, please give it a try:
[app-debug.zip](https://github.com/TheLastProject/Catima/files/6200048/app-debug.zip)

**Comment by mgohin** [comment]
Import seems to work well.

But when I open a card, I don't have the barcodes, only the card code, and the note at the bottom seems truncated


![Screenshot_20210324-205539](https://user-images.githubusercontent.com/3430304/112375271-641cb580-8ce3-11eb-87d9-4a93a4065250.jpg)

**Comment by mgohin** [comment]
For the csv file : 

```csv
Retailer;Program;Added At;Reference;Firstname;Lastname
Auchan;Carte Waaoh;2019-09-13 15:23:08 UTC;0491221702796;Stéphanie;```

**Comment by TheLastProject** [comment]
I'll fix the truncated note. Sadly the export format of Fidme doesn't seem to include any barcode information, it seems they just store the company name and have a loyalty card program database to know "Okay, company X uses Y barcodes". This could be fixed when we get #89 done, but sadly not before that. So this is as much as I can import, sadly.

I'll also look into the importing from an image file before the next release, so you could complete the info by doing Edit -> Barcode -> Edit Barcode for each card.

**Comment by mgohin** [comment]
Ok get it.

I confirm that notes are not exported (not sure it's often used).

Option to add a barcode from an image would be a good solution to me.

Without a company database I'm not sure fidme's import is convenient.

**Comment by TheLastProject** [comment]
I'll leave it implemented because it's better than nothing and maybe it'll get someone more interested in helping with #89, but I understand it is of limited use. Thanks for helping test!

**Comment by mgohin** [comment]
My pleasure.
Maybe add a little warning to explain that for now, barcode types will not be set

**Comment by TheLastProject** [comment]
I thought I did. Did the message not show up for you or did I phrase it unclearly?

![image](https://user-images.githubusercontent.com/1885159/112378585-64b74b00-8ce7-11eb-9a7d-2836568b93cd.png)

**Comment by mgohin** [comment]
Crap, didn't read 😂

**Comment by TheLastProject** [comment]
Happens :)
