### ISSUE TITLE
Direct search

### ISSUE THREAD

**Issue by comradekingu** [TheLastProject/Catima#189]
![bilde](https://user-images.githubusercontent.com/13802408/113523733-23515600-9599-11eb-87d5-983b327bce07.png)
becomes
![bilde](https://user-images.githubusercontent.com/13802408/113523723-0c126880-9599-11eb-82c5-68672780ab94.png)

Logo would maybe be better than the name(?).

**Comment by TheLastProject** [comment]
I'm pretty sure Android Design Guidelines would recommend against this. Also, none of the other apps I have on my phone do this. I'd rather stick to what users are used to instead of reinventing the wheel. If there is anything users hate, it's having to relearn how things work.

**Comment by comradekingu** [comment]
I guess the user can't really start typing away if the keyboard isn't up anyway.

**Comment by TheLastProject** [comment]
Now that you say it, that is probably one of the reasons the standard design is as it is, yeah. Pressing the search button will automatically open the keyboard.

**Comment by comradekingu** [comment]
The visual change that appears when the field is shown is what gets me.

**Comment by TheLastProject** [comment]
Well, I am just using the official Android way to show the search, so I mean, I'd rather not create custom behaviour anyway.

**Comment by comradekingu** [comment]
I guess I can't come up with anything better than
mini-logo squeezed up in the corner, 
bigger logo going transparent when searching
do away with the text logo altogether.
text logo transparent when searching.

Neither of those seem great.

Maybe logo and name only in the vacant space not filled up with cards is the way.
If the user fills it up, the user ought to know what the app is by then?
