### ISSUE TITLE
[UI] Swiping between groups is weird

### ISSUE THREAD

**Issue by jovandeginste** [TheLastProject/Catima#194]
Hi,

I just switched from Loyalty Card Keychain to your fork, and I'm happy so far! I realize there is plenty of work planned, but I wanted to provide some feedback none the less..

While swiping between groups on the main screen, I found its behavior erratic: sometimes it works, sometimes it doesn't:

* there is no visual feedback that swipe is active (you are in one group, then you are in the next)
* if I swipe slowly, I sometimes open the context menu of the card I'm holding to swipe (and this remains open after the swipe)

I'm not an Android (or Java) developer, so I'm afraid I can only provide feedback and no implemented solutions ...

**Comment by TheLastProject** [comment]
>I found its behavior erratic: sometimes it works, sometimes it doesn't

Hmm that's odd, it works really reliably for me. Maybe I swipe differently than you do. The code currently says you have to swipe right or left for at least 150 pixels, and if your swipe is more than 75% the distance vertically as it is horizontally it should ignore it (to prevent accidental swipes while scrolling). Could you try to find a pattern that you feel it should work on where it doesn't work well for you? It's always a bit of a struggle to make sure it triggers often enough but doesn't have too many false positives.

>there is no visual feedback that swipe is active (you are in one group, then you are in the next)

Yeah, that indeed can be better. I know that that's not super pretty but Android makes it actually fairly difficult to animate that nicely.

>if I swipe slowly, I sometimes open the context menu of the card I'm holding to swipe (and this remains open after the swipe)

I can reproduce this, that's definitely a bug, thank you.

>I'm not an Android (or Java) developer, so I'm afraid I can only provide feedback and no implemented solutions ...

Feedback is one of the most important parts of making a good app :)

**Comment by jovandeginste** [comment]
I think the erratic behavior mostly comes from the lack of visual feedback. When I swipe too fast or slow, i see the card menu pop up, and then I kind of hesitate.

At least I know you can reproduce. Perhaps you can cancel the menu showing after a swipe?

**Comment by TheLastProject** [comment]
>Perhaps you can cancel the menu showing after a swipe?

Yeah, definitely will do that when I get to it.

**Comment by TheLastProject** [comment]
Should be fixed in #205.
