### ISSUE TITLE
en-US title in Fastlane too long

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#199]
[!] Google Api Error: forbidden: The title for the app is too long for language en-US. - The title for the app is too long for language en-US.

So I'm reverting to the older version for now.

Ping @comradekingu

**Comment by TheLastProject** [comment]
[!] Google Api Error: forbidden: The short description (promotional text) for the app is too long for language en-US. - The short description (promotional text) for the app is too long for language en-US.

**Comment by TheLastProject** [comment]
[!] Google Api Error: forbidden: The title for the app is too long for language ru-RU. - The title for the app is too long for language ru-RU.

**Comment by TheLastProject** [comment]
![Screenshot_20210415-071144_F-Droid](https://user-images.githubusercontent.com/1885159/114818635-680c9680-9dbc-11eb-8b5d-01a901f46522.png)

F-Droid isn't happy with it either.

**Comment by comradekingu** [comment]
Hmmm.
So both title and short desc are too long?

**Comment by TheLastProject** [comment]
That's what Google says, yeah.

**Comment by TheLastProject** [comment]
So @comradekingu are you still planning to fix this or have you completely left the project? Just so I know where we stand.

**Comment by comradekingu** [comment]
Just out of time. Will get on it when I wake up.

**Comment by TheLastProject** [comment]
Okay, no rush

**Comment by comradekingu** [comment]
@TheLastProject
"too long for language ru-RU"
However RU is at exactly 50 (limit in Weblate) (changed two weeks ago though)
https://hosted.weblate.org/translate/catima/fastlane/ru/?checksum=1623401ca21ef4e9
Comments say "30".

https://play.google.com/store/apps/details?id=me.hackerchick.catima  works as it should for me in nb_NO.
https://play.google.com/store/apps/details?id=me.hackerchick.catima&hl=be&gl=US is in Cyrillic something

So, is there a problem now? What is the error description? What does the error extend to?
Most importantly, is there a penalty for running a title/desc that is too long?

**Comment by TheLastProject** [comment]
>However RU is at exactly 50 (limit in Weblate) 

Emoji are complex and there are often bugs in handling them. Maybe Google is having issues there. The fact is that Google is refusing the title.

>So, is there a problem now? What is the error description? What does the error extend to?
Most importantly, is there a penalty for running a title/desc that is too long?

I just can't use those titles, Google refuses to let me update them to these new values.

>So, what needs to be done? Cap everything at 50, starting with the original title?

Yeah I guess so.

**Comment by comradekingu** [comment]
My thinking is that the new description and features, influx of users from the old app
will mean owning "Catima 🎴 The Libre Card Wallet" is possible.

I suppose that would mean the possibility of also storing bank card details, where some cards are password-secured, for fear of negative reviews.

**Comment by TheLastProject** [comment]
That's more than 30 characters though:
![image](https://user-images.githubusercontent.com/1885159/116779237-63f79e80-aa75-11eb-999a-a6ae2545dbdc.png)

And as written in the post of #217, Google will punish apps with emojis in the app title.

Also I still think "Open" is more understandable for most people than "Libre".

**Comment by comradekingu** [comment]
@TheLastProject
"Open" isn't a keyword. In the least not something tangible for Catima as of now.
It is also likely to get overlooked, whereas "libre" means it stands out (from the plethora of options).
