### ISSUE TITLE
Long Store values should wrap

### ISSUE THREAD

**Issue by andbenn** [TheLastProject/Catima#204]
With a "maximum font size scale" set to 100, a Store field longer than 14 to 16 characters gets truncated.  It'd be nice to see this wrap on the card/detail screen, to some limit and then have ellipses.

// Example Store: 
Country Sun Sunny Rewards

// Shows as: 
Country Sun Sun...
{barcode}

// Ideally shown as:
Country Sun
Sunny Rewards
{barcode}

You probably have enough room for 2 lines of a Store in that top panel when the barcode is shown with font scale set to 100 on my phone (Pixel 3; other phone screen sizes may vary).  Does this panel have additional text layout options that you could enable?

Catima 1.13 on Pixel 3 Android 11 April update

**Comment by TheLastProject** [comment]
Should be fixed in 15f6bd86a159225c12de1001059a2cfdd8815878

**Comment by andbenn** [comment]
I just got 2.2.2, and love how the text font size adjusts to fit on the screen.  Thank you for this change!
