### ISSUE TITLE
Make cards search accent-insensitive

### ISSUE THREAD

**Issue by joriscode** [TheLastProject/Catima#206]
Currently the search is accent-sensitive. For instance, searching for `decathlon` does not return the card named `décathlon`.

This is an annoying but minor issue.

I see two approaches:
- **Modify the SQL query to ignore accents**: it seems there is no such built-in SQLite function. However, a custom _noaccent_ collation can be created and use in this query https://github.com/TheLastProject/Catima/blob/master/app/src/main/java/protect/card_locker/DBHelper.java#L502 as suggested here https://stackoverflow.com/questions/14009261/sqlite-accent-insensitive-search. This approach may require to declare all possible accents (ex: `[à, á, â, ã, ä, å, ą]` correspond to `a`) which is a significant drawback.
- **Create a search column in the table**: Java's Normalizer (https://stackoverflow.com/questions/3322152/is-there-a-way-to-get-rid-of-accents-and-convert-a-whole-string-to-regular-lette) can be used to remove all diacritics at the creation of a new card. The sanitized value would be then stored in an new column that is used for search only purposes (the existing column will remain untouched for display purposes). This implies a modification of the table schema and the difficult task of migration

**Comment by TheLastProject** [comment]
We should look into if we can set up something like [SQLite Full Text Search](https://sqlite.org/fts5.html) on Android, as it also takes care of making the search accent-insensitive.
