### ISSUE TITLE
Store self-generated barcodes of unsopported cards

### ISSUE THREAD

**Issue by ILoveFOSS** [TheLastProject/Catima#208]
As a workaround to #181 an extension of #15 would work too. As long as ZXing won't encode new or exotic barcodes, storing a self-generated one instead, would be a great workaround.

Right now I am having all my cards stored in Catima plus a picture of the one unsupported barcode in my phone's gallery. If I could put that barcode instead of the not working barcode in Catima all my issues would be solved.

**Comment by TheLastProject** [comment]
Good suggestion, I'll make that part of https://github.com/TheLastProject/Catima/issues/15#issuecomment-824179937.

Closing it as a "duplicate" of #15 to keep the issue tracker clearn.
