### ISSUE TITLE
en_US fastlane missing

### ISSUE THREAD

**Issue by comradekingu** [TheLastProject/Catima#213]
Searching for "catima google play" I got
https://play.google.com/store/apps/details?id=me.hackerchick.catima&hl=be&gl=US first result
Which is in Cyrillic…
![bilde](https://user-images.githubusercontent.com/13802408/116189561-a8530980-a718-11eb-9c89-88b5cfb54d63.png)

There is no "en_US" in https://github.com/TheLastProject/Catima/tree/master/app/src/main/res so maybe making that will fix it?

Nvm, "be" is belarusian. http://www.lingoes.net/en/translator/langcode.htm Strange nonetheless…

**Comment by TheLastProject** [comment]
en_US is the default. values refers to en_US.

I am a bit unsure what is wrong?
