### ISSUE TITLE
Language consistency

### ISSUE THREAD

**Issue by comradekingu** [TheLastProject/Catima#214]
The plugin is called "Add missing languages" now https://github.com/WeblateOrg/weblate/issues/5829

It can be turned on (project-wide) in https://hosted.weblate.org/addons/catima/catima/

I think that would help with search-results/ranking, and ultimately popularity.

Sort of depends on #199 but I think turning it on right away makes sense anyhow.

**Comment by TheLastProject** [comment]
Makes sense, enabled.
