### ISSUE TITLE
Manual setting for all font sizes

### ISSUE THREAD

**Issue by OmlineEditor** [TheLastProject/Catima#225]
please add the ability to make it possible to change the font individually for each element independently of each other.
it is very inconvenient when there is only one way to change the font through a percentage of the maximum.
see how this is done in the program Loyalty Card Keychain.

**Comment by TheLastProject** [comment]
I actually removed this because there were so many options in the options menu things were getting hard to keep an overview at. I wonder if it's possible to solve your problem without making so many settings. Which texts have font sizes that are wrong in your opinion?

**Comment by OmlineEditor** [comment]
large font with the name of the store, the label does not fit all of it. and a large font in the card number. in the list of cards you have transferred to the second line the name of the card but when displayed it is not transferred and the label is cut off
![fonts](https://user-images.githubusercontent.com/13348933/119032230-9f222900-b9b4-11eb-9553-6af0fdf35d72.jpg)

**Comment by TheLastProject** [comment]
Yeah, that is #204. Is that the only thing you want to be able to change font size for?

**Comment by TheLastProject** [comment]
Oh, that Russian translation for "Expires" is long. It's just a single word in English. Making that multiline could make sense, yeah.

The note size is actually "medium": https://github.com/TheLastProject/Catima/blob/6568ebb01c4b0fa62645dbdcc169ab78ecde28c3/app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java.

So, I guess you feel the difference between medium and large is too small? https://github.com/TheLastProject/Catima/blob/a93d240d9a7049af69c406260b1c2baba367e853/app/src/main/java/protect/card_locker/preferences/Settings.java#L69-L82

**Comment by OmlineEditor** [comment]
the difference in fonts between large small and medium is insignificant for me. I think we need to return and make it possible to make the font size individually for each field. make advanced settings to change the all font size.

**Comment by TheLastProject** [comment]
Sorry for leaving this open for so long. I'm not going to work on this, there were already bugs where some elements were missing options and I'm not going to risk reintroducing those bugs. I probably also won't accept patches for this.
