### ISSUE TITLE
change the color of the main menu and buttons

### ISSUE THREAD

**Issue by OmlineEditor** [TheLastProject/Catima#228]
Please add the ability to change the default menu color and change the color of the buttons. a good example of this can be found in the program Aurora Store: https://f-droid.org/ru/packages/com.aurora.store/

![color](https://user-images.githubusercontent.com/13348933/119275709-3f7b8600-bc1f-11eb-967f-3312887b0899.jpg)

**Comment by TheLastProject** [comment]
I'm not interested in writing support for this myself as this is the theming colours I chose for Catima. But I will accept a pull request that adds this feature in an easy-to-maintain way.

**Comment by subhashishanand** [comment]
@TheLastProject I would love to add the feature to the app. Can I take this up?

I will add a Theme color feature in the Setting(User Interface) section and provide multiple theme colors option to change.

**Comment by TheLastProject** [comment]
Sure! What is your plan for the secondary color (the yellow pencil button in the screenshots) though? Will you just pick a decent colour that fits the main colour?

**Comment by subhashishanand** [comment]
@TheLastProject I shall provide such multiple colors which fit with pencil button color ( yellow ) and look decent.

**Comment by TheLastProject** [comment]
Makes sense, if people want colours that don't fit with the pencil we can later extend the feature then.

Go ahead :)

**Comment by subhashishanand** [comment]
@TheLastProject  ok sure.

**Comment by subhashishanand** [comment]
Can you please review my PR?

**Comment by TheLastProject** [comment]
You seemed to have accidentally pointed your PR at the master branch of your own fork instead of this repository. Could you [please recreate it](https://github.com/TheLastProject/Catima/compare/master...subhashishanand:%23228Issue) so the tests can run on your branch too? :)

**Comment by subhashishanand** [comment]
done. please check that:)

**Comment by TheLastProject** [comment]
Fixed in #340, thank you @subhashishanand!

**Comment by subhashishanand** [comment]
@TheLastProject  welcome :)
