### ISSUE TITLE
Barcode ID not part of export

### ISSUE THREAD

**Issue by ILoveFOSS** [TheLastProject/Catima#235]
I have just tested https://github.com/TheLastProject/Catima/commit/929633e4dda0382a93bf10a82a5d9414f3627c47 and afterwards exported all my cards, transferred the CSV to my 2nd phone running Catima, deleted all app data on the 2nd phone and imported the CSV. After the import, all cards with differing barcode values and card IDs used the Card ID as the barcode value.

Looking at the CSV it seems as only the card ID is exported but not the barcode value.

**Comment by TheLastProject** [comment]
Oh, I forgot to export that field apparently...

https://github.com/TheLastProject/Catima/blob/master/app/src/main/java/protect/card_locker/importexport/CsvDatabaseExporter.java#L53-L62

**Comment by TheLastProject** [comment]
Should be fixed in fb36aecf42b7af57fffe9a8444dccceaf7eae104.
