### ISSUE TITLE
Card should be saved to the currently selected group

### ISSUE THREAD

**Issue by t351206** [TheLastProject/Catima#248]
When I am currently in a group tab and I want to add a new card to this group the currently selected group should be pre-selected.

**Comment by TheLastProject** [comment]
That makes total sense. Would be pretty easy to implement too: just add an extra field to the intent that is given to the new card code and do an if statement with that.

**Comment by TheLastProject** [comment]
Fixed in c5b1718e8e5a1fa13eb9e1844f8d37d868473ea5.
