### ISSUE TITLE
UPC_E not displayed

### ISSUE THREAD

**Issue by sphh** [TheLastProject/Catima#252]
I finally got my ‘EU Digital COVID Certificate’ with a huge QR code.

I thought, it would be a good idea to put this code into Catima, so that I have it with me all the time. I could scan it from inside Catima and it tells me, that it is a `UPC_E` code. Unfortunately Catima can not display it.

Do you think, this can be solved? Could you also give this a high priority, since I believe more and more people would like to but this code into their wallet? Thanks!!!

**Comment by TheLastProject** [comment]
So... it turns out support for UPC-E was added to zxing years ago but it was just not noticed and never enabled in Catima. I enabled it now and created #253.

I've attached a debug build with UPC-E support, could you confirm if it also works for your QR code? If so, I'll include this support the next release.

[app-debug.zip](https://github.com/TheLastProject/Catima/files/6778973/app-debug.zip)

**Comment by sphh** [comment]
Oh, that was quick!

The good news is, that I can select the UPC-E barcode and that the value is displayed.

The bad news is, that Catima reads the QR-code but thinks it is a UPC-E barcode, so it looses a lot of characters. Even if I then select `QR code` to be displayed, it is the smallest QR code I have seen with just 8 digits.

I then scanned the QR code with `SecScanQR`, copied the scanned value to Catima and used this to set the barcode value with display type `QR code`. This works (well, I get a QR code displayed, have not tested it, if it is valid).

It looks to me, that Catima detects the QR code as a barcode …

**Comment by sphh** [comment]
I just checked the generated QR code (which is different to the scanned) and I can confirm, that it works.

**Comment by TheLastProject** [comment]
Could it have been bad lighting conditions? SecScanQR uses the exact same library as Catima, so it would surprise me if Catima really misunderstands the QR code while SecScanQR doesn't. I managed to scan my own COVID QR code from https://coronacheck.nl/en/print/ just fine.

**Comment by sphh** [comment]
Maybe …

I scanned the code with `Catima` and `Catima debug` and both times I got a UPC-E barcode. `SecScanQR` gave a QR code.

Now I tried it again with the desk lamp very close. Here I got unreliable results with both programs (`Catima` and `SecScanQR`). I believe we can say, that this looks like a camera problem indeed (my camera is not the best and rather low resolution).

Should we close this issue? (But thanks for implementing UPC-E barcodes, even if this was not the original problem!!!)

**Comment by TheLastProject** [comment]
Yeah, I think #249 should help make scanning more reliable under different lighting conditions.

I'll close the issue yeah, but thanks for helping me fix an unrelated bug :)

**Comment by djechelon** [comment]
I successfully showed the QR at least a couple of times and was allowed in. Catima is now my (easier-to-use) official EU digital pass wallet despite having another official open source [wallet app](https://play.google.com/store/apps/details?id=it.pagopa.io.app).
Scanned with [Verifica C19](https://play.google.com/store/apps/details?id=it.ministerodellasalute.verificaC19)

Just wanted to share this information. I understand the topic may be a bit oudated.

**Comment by sphh** [comment]
Yesterday I had my first successful scan myself.

Previously the green pass QR was mainly visually inspected and deemed as valid!:roll_eyes:

On two occasions the scan failed, because the other smart phone could not read the QR code. The possible reason is, that the edges of the code displayed are fuzzy – maybe because of my tiny screen?

**Comment by TheLastProject** [comment]
Catima should make sure the codes aren't blurry no matter the screen size though. That should be a new issue then

**Comment by sphh** [comment]
Regarding the blurred QR code, see #329.
