### ISSUE TITLE
Add language selector

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#272]
Some manufacturers remove languages. As an example, while Somali is available on Android 7 and up in AOSP, it seems to be disabled on some phones (like a Motorola phone someone else who checked has).

We should add a language selector to make sure users are not limited by manufacturers doing weird stuff like that.

**Comment by Mejans** [comment]
Or the language may not be available on Android, like Occitan, so we have no way to enable it within the software =/

**Comment by TheLastProject** [comment]
I fixed this now, I hope you enjoy your Occitan translation @Mejans :)

**Comment by Mejans** [comment]
Will try this tomorrow! Many thanks!
