### ISSUE TITLE
Possibly unused string offered for translation

### ISSUE THREAD

**Issue by StoyanDimitrov** [TheLastProject/Catima#274]
I'm searching for context of the `card_selected` key (Selected:). I fail to find it used in the code. I can locate it in the UI. Can you provide guidance?

**Comment by TheLastProject** [comment]
It is supposed to be used when you long-press a card in the main screen, but now that you mentioned it I noticed it isn't actually being used. That is a bug, I'll fix that. But for context: it's the text that appears at the top of the screen in the main screen when you long-press a loyalty card

**Comment by StoyanDimitrov** [comment]
Alright, what string is used then?

**Comment by TheLastProject** [comment]
Fixed in b6ef6806a01160b7242b6845d1ba380d6964516b (where I made a typo in the commit message, oops...)

The new correct string name selectedCardCount (which is a plural format, as it should be). It should be translatable on Weblate now. Thank you for reporting this issue!
