### ISSUE TITLE
Two strings with possibly equal meaning

### ISSUE THREAD

**Issue by StoyanDimitrov** [TheLastProject/Catima#279]
`addFromImage` - Select image from gallery
` chooseImageFromGallery` - Choose image from gallery

Ideally the text of the two should be the same to leverage the powers of computer assisted translation tools as well as UI uniformity.

**Comment by TheLastProject** [comment]
Fixed in efdb0dd6bb5a2968e3133893d6a25db0bf515f89, thank you for reporting!
