### ISSUE TITLE
Export date not correctly displayed

### ISSUE THREAD

**Issue by leManu** [TheLastProject/Catima#280]
It looks like expiry date is not correctly displayed. The date is showed into an <xliff:g> XML tag (see provided screenshots below).

Catima installed version is 1.14.1 from F-Droid, with french locale.

![Screenshot_20210716-174404_Catima](https://user-images.githubusercontent.com/2826452/125975437-41deb5b7-9ec6-48d4-95e8-d96d55d5d2f0.jpg)

![Screenshot_20210716-174343_Catima](https://user-images.githubusercontent.com/2826452/125975464-525f4e81-d044-45e8-80a2-3a34272ed004.jpg)

**Comment by TheLastProject** [comment]
Fixed in 05fd629ad41198449fa5cb98fc2ef26cdaf0f314, thank you for your report!
