### ISSUE TITLE
Max brightness barcode only on fullscreen

### ISSUE THREAD

**Issue by arix00** [TheLastProject/Catima#297]
Currently if I turn off "brighten barcode view" it's normal brightness on fullscreen.
Can you change it to(or add an option): use normal brightness on card view and max brightness on fullscreen barcode view. 

Also is it possible to show fullscreen barcode in landscape mode?

Thanks.

**Comment by TheLastProject** [comment]
Could you please explain your use case for not using full brightness until you tap the loyalty card to make it full screen?

And fullscreen landscape barcode is already possible, just switch to landscape mode before tapping the barcode.

**Comment by arix00** [comment]
1. I usually get the card ready in card view page while waiting on line, and show the fullscreen barcode for cashier during checkout if necessary. In many cases card scanned just fine in normal brightness, so I never need card view page in max brightness, but fullscreen +max brightness is a must have failsafe.

2. Yes it's possible however my phone is locked in portrait mode, as browser/VLC handle landscape fullscreen video playing just fine, I wouldn't change that for Catima. Or can you please add another option for that: portrait/landscape/follow system.

Thanks.

**Comment by TheLastProject** [comment]
1. I assume you are worried about the battery usage of leaving the screen on max brightness while waiting in line? If you have "Prevent lock screen" enabled in settings, Catima will ask Android to stay above the lock screen while displaying a loyalty card. In that case, when you turn off your phone's screen (to save battery), Catima will show up when you turn your screen on again and Android won't show your phone's lock screen until you try to leave the LoyaltyCardViewActivity. Won't that also satisfy your use case?
2. What Android version are you using? On recent Android versions, as long as you don't have "Lock barcode orientation" enabled in Catima settings, you should get an icon in the bottom right corner allowing you to rotate even if you have your device locked to portrait mode. But I guess I may need some logic for older Android devices there.

**Comment by arix00** [comment]
Thanks for the reply! 

1. Yes it should work but that's one extra power button. It's just annoying to viewing a full bright screen. Another case is editing/checking card then you definitely wouldn't want it.

2.  Oneplus running Android 11...
Actually I think I found a bug: with auto rotate on and "lock barcode orientation" off, in portrait full screen view, rotate phone. I expect a rotated full screen but it's a rotated card view. 

TBH I think these two "features" should be fairly easy to implement so why not give us some flexibility?

**Comment by TheLastProject** [comment]
1. You can already bypass the brightness if you want to edit by long-pressing a card and choosing edit. So that only leaves wanting to view to barcode explicitly in the viewing activity which I am not sure why anyone would do except with the intent to have it scanned.
2. Oh, yup, that is definitely a state bug. Thanks, will fix that.

>TBH I think these two "features" should be fairly easy to implement so why not give us some flexibility?

Writing an app is more about just adding features, [it's about finding a careful balance between having the features people want and not being complex and overwhelming by having too many buttons. And I am not really convinced yet this one is really worth another button in the settings](https://ometer.com/preferences.html).

**Comment by TheLastProject** [comment]
Okay, the fullscreen state loss is fixed in 1960fb0b6a0b5eed8b657ed561ace84369b6ad3b.

**Comment by arix00** [comment]
How about change the option to max. bright on card view only? Same reason for 2nd issue I'd rather have a fixed landscape fullscreen display. 

I believe max brightness+largest barcode should be the default failsafe behavior and leave all the adjust settings to card view.

Thanks.

**Comment by TheLastProject** [comment]
I'm not convinced this is an improvement, sorry.

**Comment by ghost** [comment]
@TheLastProject please implement this feature. It becomes even more important with support of pkpass. If you want to look at the info of those cards you get blasted by the max brightness. Please let us view and ready all card Infos in normal brightness and only switch to max brightness on fullscreen barcode.
Thank you so much for all your wonderful work.

**Comment by TheLastProject** [comment]
I understand getting blasted in the face with max brightness can be uncomfortable. However, if the brightness is not increased, this has serious chance of scanning of cards failing. Most people don't even know the full screen mode exists, so implementing this will break card scanning for a lot of people. 

You can long-press a card in the main screen and click edit to go straight to the edit screen, which won't increase your brightness (only the view screen does), so there is a way to view card info without brightness increasing while leaving the setting on. Alternatively, you can disable the brightness setting in settings and manage your screen brightness yourself.

So no, my answer remains no, I won't implement this. It will break too much for too many people and workarounds exist.

**Comment by ghost** [comment]
Understand. What do you think about adding "view info" to the long press menu? As I don't want to edit anything in this case but view the Info related to the card.

**Comment by TheLastProject** [comment]
You can just not make any changes in the edit view. I see no reason to justify all the extra complexity and maintenance burden of an extra view, sorry.
