### ISSUE TITLE
Color Picker Stopped Working

### ISSUE THREAD

**Issue by zjullion** [TheLastProject/Catima#302]
Saved five cards in Catima - went to save a sixth card, and the color picker no longer works. I am able to select colors (custom and pre-generated), but the card color does not update.  All other aspects of saving / updating cards appears to work normally.

I tried restarting the app and the phone but no luck.

Phone is a Samsung Galaxy A50 (SM-A505W) running Android version 11.

**Comment by TheLastProject** [comment]
What version are you on? This should have been fixed in 2efb666fae0dcaaae1b60ca1b3929f5fe05e6991 already, which is part of Catima 2.0.4

**Comment by zjullion** [comment]
My bad, didn't realize there was an update! It is indeed working with the newest version.

**Comment by TheLastProject** [comment]
Thanks for getting back to me and confirming it works for you again :)
