### ISSUE TITLE
Add Changelogs To F-Droid

### ISSUE THREAD

**Issue by seniorm0ment** [TheLastProject/Catima#355]
When updates are pushed to F-Droid, it doesn't show the changelogs.
Suggesting adding changelogs to F-Droid.

**Comment by TheLastProject** [comment]
Providing this means putting the changelogs into Fastlane, which means that there are suddenly a lot more things to translate and we're already low on translators and most languages take more than a week to update, so they would never translate the changelog in time for a release. Also, most people don't see to care about changelogs?

I don't know, I guess I could be willing to start doing this under the condition that there will be a script to change the Fastlane changelogs back into the CHANGELOG.md (or maybe the CHANGELOG.md should be parsed to create Fastlane changelogs so I only have to bother with CHANGELOG.md myself).

I guess I'll experiment a bit with seeing how much work it would be to have a script that automatically writes the CHANGELOG.md to Fastlane files and maybe creates a per-language CHANGELOG.md for on the website? That way even if the translations are late they could still be useful on the website anyway.

**Comment by seniorm0ment** [comment]
Do they have to be translated? It's not like the ones pushed through GitHub are translated correct?

**Comment by TheLastProject** [comment]
Well, Weblate will pick it up because it becomes part of Fastlane. I guess I could try to see if I can make Weblate disable that but that seems even more confusing to people.

I guess I'll just have to bite the bullet :)

**Comment by TheLastProject** [comment]
Fixed in 6223ccd4bc672e106169839059b4cc2a930ca828.

**Comment by IllusiveMan196** [comment]
Aha, so we don't necessarily have to translate them? Don't know how mythical "most people" behave, but when I read changelogs it is mostly for newest app version.

**Comment by TheLastProject** [comment]
Yeah, feel free to ignore old changelogs. I want to actually also put the full changelogs on the website but honestly, changelog is the least interesting part to have translated :)

**Comment by IllusiveMan196** [comment]
Everything else is done already, now going over some older translations to see if anything can be improved (shortened, paraphrased, etc, etc) to stay unchanged unless really necessary or something new needs to be added.
