### ISSUE TITLE
Feature Request: Swipe to scroll between cards

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#36]
<a href="https://github.com/thecybrid"><img src="https://avatars2.githubusercontent.com/u/19598466?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thecybrid](https://github.com/thecybrid)**
_Tuesday Nov 06, 2018 at 01:57 GMT_
_Originally opened as https://github.com/brarcher/loyalty-card-locker/issues/281_

----

Requesting a feature to allow swiping to scroll between cards, rather than having to return to the main screen and select an alternate card.

**Comment by arshbeerSingh** [comment]
Can I work on this issue?

**Comment by TheLastProject** [comment]
I'm actually not sure if this really is an useful feature. Like, how likely is someone to want to swipe to the next loyalty card? You always want a specific card, going previous/next seems to take longer than moving back to the main menu and selecting the card you want. I think this issue is probably best closed with the request not implemented.
