### ISSUE TITLE
Pressing "back" switches to the "All" group

### ISSUE THREAD

**Issue by di72nn** [TheLastProject/Catima#370]
Pressing the "back" button (while the main screen of the app is open) switches to the "All" group/tab. I don't believe that should happen.
I think this is a straightforward issue, but I can provide rationale if needed.

Thank you for working on the project!

**Comment by TheLastProject** [comment]
This is actually intentional. Non-technical users easily end up getting themselves stuck in an unintended situation by pressing something accidentally and not remembering or understanding what they did. Because of that, having the back button reset you to the "standard" state if you press it often enough is very helpful.

I do understand that this behaviour can also be annoying for those of us who want our default view to not be all cards. Personally, I just remember to leave the app by using the home button instead of the back button if it is in a state I want it to stay at, which is consistent with how you would do this for every single Android app. I personally think that that should be sufficient and consistent with the rest of the Android ecosystem to be reasonably self-explanatory, but I am willing to discuss how to otherwise improve this without getting rid of this failsafe for confused users accidentally getting themselves stuck in an unintended state.

**Comment by di72nn** [comment]
Hmm, I see. I think this is a well-intended, but flawed approach ¯\\\_(ツ)_/¯

> Non-technical users easily end up getting themselves stuck in an unintended situation by pressing something accidentally and not remembering or understanding what they did.

Well, I think the users either don't have groups or understand it well enough to **create** groups in the first place.

> having the back button reset you to the "standard" state if you press it often enough is very helpful

Resetting things is not a function commonly associated with the back button, so it is not really expected. More on navigation-related cases below.
This is also based on the assumption that "All" is the "standard" state, which is not generally correct (for example, I have a "main" group with a couple of cards and everything else is kind of "in the archive").

> I do understand that this behaviour can also be annoying for those of us who want our default view to not be all cards.

It's not just a subjective annoyance, the "open on the last used" and "default to all" approaches clash with each other.

> Personally, I just remember to leave the app by using the home button instead of the back button if it is in a state I want it to stay at, which is consistent with how you would do this for every single Android app.

Yes, "going home" works consistently, but this is only one part of Android's navigation patterns. The other one, at least as common as the first, is navigation through Android's activity back stack. Granted, Catima is not usually started from another app, but it's not a good idea to violate the expectations set by all the other apps.

That's a niche example, but here's how I get reminded about the issue:
I update my apps via F-Droid, then go through the list of updated apps and open each one using the "open" button in the F-Droid app, check that the update didn't make my phone explode or something, **then go back** to the F-Droid app with the back button.
It works consistently across the majority of apps, but with Catima I have to train myself to do recent-apps-juggling (returning to F-Droid via the "recent apps" menu). (Ok, I guess in this case the apps are started as separate tasks, rather than being in the stack of the same task, but the back navigation is expected to work the same).

From my experience with Android, the back button either takes you back (to the previous activity/app in the stack) or undoes some in-app navigation/actions. Catima kind of does the latter, but not really: the app starts with the *last used* group being active, but (even if there was no in-app navigation/actions performed since start) the back button takes you *"forward"* to the "standard" state.

I guess an option to define the default group would solve this. However, if a user went to such great lengths as to define a different default group, I don't think they need any assistance in resetting to the default state at all: the app should just open with the default group active (or with the last screen state if Android provides the `savedInstanceState`).

Actually, the "failsafe" would work even better with the option to define the default group: when the user uses the back button, Android destroys the activity and its state, so the next time it is opened, the state is "default". Same for removing the app from "recent apps". But pressing "home" and returning would restore last state. This is very common and Android's been training users to expect such behavior for years.

Sorry for making such a big deal out of a petty issue like this, but I guess this inconsistency bothers me that much :-)

**Comment by TheLastProject** [comment]
No need to apologize, I appreciate the clear write-up and I now agree that I misjudged the value of the pros and cons.

I think the best would be to just remove the snippet of code that sets group to all on pressing back. After all, why set a default in settings if the default can just be whatever you last chose :)

**Comment by TheLastProject** [comment]
Fixed in 9ba07982bffce0fa20bce021813fe38ab27f4e47.
