### ISSUE TITLE
Support for cropping/straightening images

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#372]
(As asked through email)

It would be nice if Catima let you straighten and crop the card images

**Comment by TacoTheDank** [comment]
@TheLastProject I'd recommend using https://github.com/CanHub/Android-Image-Cropper instead, as it's a maintained fork of the above with important bugfixes for newer Android versions and whatnot.

**Comment by TheLastProject** [comment]
@TacoTheDank This is currently being implemented in #559 using https://github.com/Yalantis/uCrop
