### ISSUE TITLE
OCR support

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#373]
(As requested by email)

It would be nice if Catima could OCR added images.

One possible workflow (suggestions welcome):
1. Go to Photos
2. Select image
3. Catima OCR scans (for example: it finds the text "la place 12")
4. Catima suggests if the user wants to add the found text (for example: "la place 12") to the notes

Important note: this needs additional testing to ensure it works well enough in practice to be worth implementing. Useless suggestions are worse than no suggestions.

**Comment by IllusiveMan196** [comment]
After testing a number of already existing OCR (card reader) apps there are couple things from user perspective:
Language support: cyrillic and latin-based languages would require different approach (so far only Google Translate works reliably, Samsung, ABBYY or any other app lags behind. Samsung doesn't even recognize cyrillic language)
Color difference: some cards have non-standard design, which doesn't really play well with OCR. Foil, white-on-black, etc.

Here as it would save just store name, website and possibly card holder name (?) or additional notes, part of all this is less relevant than for e.g. business cards.

**Comment by TheLastProject** [comment]
So, if I understand you correctly, your opinion is that this is not useful as it won't really be possible to make it work reliably enough?

**Comment by IllusiveMan196** [comment]
Mostly yes, though I don't really use this functionality except as part of Google Translate or have tens of cards to digitize. It may be possible to make OCR work reliably enough, but I have no idea how (Google did it somehow after all).

**Comment by TheLastProject** [comment]
Yeah, I think I'll just close this as wontfix. So much extra code and complexity for so little gain...
