### ISSUE TITLE
Make barcode text in view copyable

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#389]
And maybe support selecting and copying text in the more info part of the view while we're at it.

**Comment by digital-castle** [comment]
I am looking for a good first issue. I have not contributed in the past. I would like to help with this if you could be patient with me.

**Comment by TheLastProject** [comment]
Yeah sure, feel free to take this on :)

Some hints: these things are defined in Android's layout resources (xml files). It is probably easiest to see if there is another (non-editable) text field that allows you to select the text in it and see  how it is defined. Or web search :)

**Comment by Kushagrasaxena-13** [comment]
I want to work on this issue

**Comment by TheLastProject** [comment]
@digital-castle are you still interested in this? Otherwise I will give this issue to @Kushagrasaxena-13

**Comment by digital-castle** [comment]
I am very sorry. My whole family tested positive for Covid. Life has been crazy. Go ahead and pass it off. Fran
-------- Original message --------From: Sylvia van Os ***@***.***> Date: 9/17/21  10:57  (GMT-05:00) To: TheLastProject/Catima ***@***.***> Cc: digital-castle ***@***.***>, Mention ***@***.***> Subject: Re: [TheLastProject/Catima] Make barcode text in view copyable (#389) 
@digital-castle are you still interested in this? Otherwise I will give this issue to @Kushagrasaxena-13

**Comment by TheLastProject** [comment]
@digital-castle Oh no, that's some heavy stuff... Best wishes for you and your family! May they have a speedy recovery!

@Kushagrasaxena-13 Go ahead and take this on then :)

**Comment by aditya3901** [comment]
https://user-images.githubusercontent.com/79566784/135743454-c62449ef-be94-4802-b79a-e66284c9b99c.mp4


Is this what was supposed to be done?

**Comment by aditya3901** [comment]
https://user-images.githubusercontent.com/79566784/135743656-3f2373a1-6495-487f-849d-d674314e0133.mp4

Is this what was supposed to be done?

**Comment by aditya3901** [comment]
![WhatsApp Image 2021-10-03 at 12 37 08](https://user-images.githubusercontent.com/79566784/135743880-4fd57ae1-52bb-4f63-99be-0abf63b7f92c.jpeg)

Check please. Is this what was supposed to be done?

**Comment by TheLastProject** [comment]
Yes, that was the whole task :)

Although being able to copy from more info would be nice as well (if you for example set an expiry date, you get a button at the bottom you can click to see more info)

Given I haven't heard from @Kushagrasaxena-13 in 2 weeks, I hope they won't mind if I give this task to you.

**Comment by aditya3901** [comment]
Ok I'll work on that. Kindly see the updated pr I made for the about page #441. I made the changes you mentioned.

**Comment by Kushagrasaxena-13** [comment]
> Yes, that was the whole task :)
> 
> Although being able to copy from more info would be nice as well (if you for example set an expiry date, you get a button at the bottom you can click to see more info)
> 
> Given I haven't heard from @Kushagrasaxena-13 in 2 weeks, I hope they won't mind if I give this task to you.

ok sir i will

**Comment by TheLastProject** [comment]
Hey @aditya3901, I haven't heard from you on this for a while. If you still want to work on this, please tell me. Otherwise I will free this up for someone else to work on.

**Comment by aditya3901** [comment]
My apologies. I'm actually busy at this moment with my college exams and stuff. 
I'm unable to find the "more info" layout you mentioned. If you can kindly mention the layout file, I'll make the pr by today itself. We just have to add 3 - 4 more attributes to the textview for this issue.
Else you can free this up. I'll get back to it later.

**Comment by aditya3901** [comment]
So like I should make these textviews copyable as well right?
Ok.. check the pr then..
