### ISSUE TITLE
[Feature Request] Encrypted Backups

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#40]
<a href="https://github.com/trymeouteh"><img src="https://avatars3.githubusercontent.com/u/31172274?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [trymeouteh](https://github.com/trymeouteh)**
_Wednesday Dec 12, 2018 at 21:36 GMT_
_Originally opened as https://github.com/brarcher/loyalty-card-locker/issues/285_

----

When you export a file it is not encrypted and this can be a concert when your backing this file up to cloud storage. Please add the ability to encrypt a file when it is backed up with a password and when you import the file it will as for the password to import the data.

**Comment by TheLastProject** [comment]
<a href="https://github.com/trymeouteh"><img src="https://avatars3.githubusercontent.com/u/31172274?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [trymeouteh](https://github.com/trymeouteh)**
_Tuesday Sep 17, 2019 at 02:37 GMT_

----

I would like to suggest using 7z. 7z are compressed files, therefore all you will need to do is integrate 7zip into the app and when it does the export, you will set a password and it will create the backup file and then out it inside a compressed 7z file with a password.

**Comment by trymeouteh** [comment]
I would like to suggest 7z or gz as an option since they both support encrypted password protection.

**Comment by djechelon** [comment]
Shouldn't be Google Drive backups encrypted with the old phone's PIN? I am definitely sure about it. If privacy is a concern, one would not (as I did before A10) enable GDrive backups

**Comment by TheLastProject** [comment]
I am thinking it may make most sense to add an option to send the backup data to another app instead of writing it to SD card directly. Something like OpenKeyChain. That way we can also be sure the encrypting and decrypting is done by an app following best security practices.

**Comment by IllusiveMan196** [comment]
Maybe [Aegis Authenticator](https://github.com/beemdevelopment/Aegis) can be used as a reference? It has password encrypted backup option, scheduled backups and biometric unlock. Before doing it all though best would be to contact devs - beemdevelopment. Basically you could solve this issue and app password protection as well.

**Comment by seniorm0ment** [comment]
Yes, I would agree. The encryption would be best to be sent and handled to another app such as OpenKeychain with PGP.

Another more complicated idea would be to offer the data as an export into a format that can be imported into Keepass (CSV?). But it would allow more universability if a user wanted to migrate the data away from Catima for whatever reason.

**Comment by TheLastProject** [comment]
Well, it looks like I'm going to implement this as a way to password-protect a .zip export. Reason as follows:

1. Stocard supplies password-protected zip files when you ask for your data, so I have to support opening password protected zip files
2. Next Catima release will support images (see #15) and it just makes sense to change exporting from .csv to .zip to make it easier for end-users to use their data in other programs if wanted (and it will take less space than base64-encoding the image as text)
3. The library I chose to read password-protected zip files ([zip4j](https://github.com/srikanth-lingala/zip4j)) supports using AES encryption mode to create password protected zips too very easily: https://github.com/srikanth-lingala/zip4j#creating-a-password-protected-zip-file--adding-files-to-an-existing-zip-with-password-protection

Not quite sure how secure the AES implementation is though, but I hope this will still make y'all happy anyway without making me spend a lot of time on this?

**Comment by TheLastProject** [comment]
I am tagging this as "good first issue" because the only things needed to implement this would be a dialog to enter the desired password and setting the password for zip4j to use in the export. Should not be very hard for anyone interested in this feature to pick up.

**Comment by TheLastProject** [comment]
Well, in this case the easiest thing would probably be to start with the unit test. That way you can try your changes very quickly.

So first, copy the `multipleCardsExportImport` to `multipleCardsExportImportPasswordProtected` or something like that: https://github.com/TheLastProject/Catima/blob/2128f0a601b5affd660ad6dd15e88026f6e3b92d/app/src/test/java/protect/card_locker/ImportExportTest.java#L326-L355

Make up some password, replace null in the `importData` line with that password and add a new password parameter with the same password to `exportData`.

Then, modify the `exportData` function to encrypt the data with a password if the password value is not null, as written in the zip4j documentation: https://github.com/srikanth-lingala/zip4j#creating-a-password-protected-zip-file--adding-files-to-an-existing-zip-with-password-protection.

After that, expand the export code to create a dialog and ask the user for a password they want to use: https://github.com/TheLastProject/Catima/blob/2128f0a601b5affd660ad6dd15e88026f6e3b92d/app/src/main/java/protect/card_locker/ImportExportActivity.java#L408-L422.

Feel free to make the pull request early in development and mark it as Draft so I can guide you along the way.

**Comment by TheLastProject** [comment]
The zip4j documentation indeed seems to be slightly lacking. Looking at https://github.com/srikanth-lingala/zip4j/blob/2ec68db8b7dcac1e6867362c3cb1c80d5d793762/src/main/java/net/lingala/zip4j/io/outputstream/ZipOutputStream.java#L52-L54, it seems you can define a password in ZipOutputStream. Maybe that'll work?
