### ISSUE TITLE
Turn reverse in sorting into a checkbox

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#401]
I've been told the sorting system is a bit confusing.

It's probably best to, instead of having a "Reverse" button, to have "Reverse" be a checkbox below the sorting options.

This may require a custom dialog box layout, because now we're no longer making just a list, but it still shouldn't be that difficult (in fact, Creating/Renaming a group already uses a custom layout) and pretty doable for an Android beginner.

**Comment by QuangDNguyen2211** [comment]
Hi, I would like to work on this issue. Do you mind giving a little bit more description? From what I understand, you want the reverse button to be changed into a checkbox like name, last used, and expiry, and placed under expiry?

**Comment by TheLastProject** [comment]
Name/Last Used/Expiry are current radio buttons. I want Reverse to become a checkbox below that yes.

So it now looks like this:
![image](https://user-images.githubusercontent.com/1885159/133985207-e67d3ffc-141a-4aaa-a65c-e379acf3e8c3.png)

And I want it to look like this:
![photo5929186186327340543](https://user-images.githubusercontent.com/1885159/133985231-0f8b1683-746b-4c05-98e2-6b417f3228e7.jpg)

I'll assign this issue to you, tell me if you need more info or help :)

**Comment by QuangDNguyen2211** [comment]
Hi, I finished changing the reverse button to a checkbox. Can you show me how you want me to make a pull request? Thank you

**Comment by namra4122** [comment]
hello I would like to try can u please assign me

**Comment by TheLastProject** [comment]
Sorry, this was already fixed in https://github.com/TheLastProject/Catima/commit/4e0ecaa7be69ace4094fd9b45d6a6450f05a44ae but I forgot to close this issue
