### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#402]
Good way to contribute for those who can't code!

Sadly, Hacktoberfest won't count commits made by Weblate. So you'll have to do it the manual way.

1. Fork this repository
2. Download [Android Studio](https://developer.android.com/studio)
3. Make changes with the [Translation Editor](https://developer.android.com/studio/write/translations-editor)
4. Create a Pull Request with your changes

Hopefully in the future Hacktoberfest will also count translations from systems like Weblate.

**Note**: Please only translate languages you know. Nobody likes Google Translate...

**Comment by rohanbabbar04** [comment]
Hi I would like to translate 
So I can translate in any language right?

**Comment by TheLastProject** [comment]
Yeah, every language is accepted :)

**Comment by pxn** [comment]
Weblate allows only 500 chars for translated strings, even when english string is longer than 500 chars (mainly problem in Fastlane).
Found this in Weblate docs: https://docs.weblate.org/en/latest/user/translating.html?highlight=translated%20string%20lenght#translated-string-length - probably not best solution, translation might be longer that original by 10-20%, i guess.

**Comment by TheLastProject** [comment]
Which string are you trying to exactly translate? Google has different limits on different kind of string.

**Comment by pxn** [comment]
One example https://hosted.weblate.org/translate/catima/fastlane/cs/?checksum=1224be202a812d52

**Comment by TheLastProject** [comment]
This is not a Weblate issue, Google allows release notes to only be up to 500 characters long. So Weblate limiting you to 500 characters there is correct.

**Comment by IllusiveMan196** [comment]
What changed in Fastlane full app description? It shows as untranslated but source seems to be almost the same (translation as well)

**Comment by TheLastProject** [comment]
I removed the cat face from the full description in every language, I guess Weblate didn't like me doing that. Sorry for the false alert on full description.

Changelog translation is very low priority yes

**Comment by avikkundu** [comment]
want to work on it.

**Comment by TheLastProject** [comment]
Go ahead! I'm not going to assign this issue to a single person as there are many difference languages to work on, but go for it :)

**Comment by rishit-khandelwal** [comment]
Can i work on translating to hindi

**Comment by TheLastProject** [comment]
Sure :) I don't know if @rohanbabbar04 is still planning to (given they're from India too). There is definitely enough stuff to translate for 2 people, but good idea to check with each other to make sure you're not doing double work :)

**Comment by TheLastProject** [comment]
Closing this as Hacktoberfest is over and there's a link in the README too.
