### ISSUE TITLE
Migrate to Android 12 Splash Screen

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#407]
https://developer.android.com/about/versions/12/splash-screen-migration

**Comment by rohanbabbar04** [comment]
Hi If this issue is not worked upon yet would like to work on it. @TheLastProject

**Comment by TheLastProject** [comment]
Go for it! :)

**Comment by rohanbabbar04** [comment]
Hi @TheLastProject I am also participating in hacktoberfest  so can you mark hacktoberfest label on it

**Comment by TheLastProject** [comment]
I don't think that label is necessary for issues, only for the repo. But sure, why not :) Done!

**Comment by TheLastProject** [comment]
Fixed in https://github.com/TheLastProject/Catima/commit/234356f8f2625fa108d4675860c09869dd2d8478
