### ISSUE TITLE
Improve about screen

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#418]
[StreetComplete](https://github.com/streetcomplete/StreetComplete) has a really nice about screen, very organized and linking to translations and all.

I want something like that for Catima too :)

![image](https://user-images.githubusercontent.com/1885159/134771587-c1e7bc41-257b-47a4-82f5-0806bef7244b.png)

**Comment by roshaan005** [comment]
can I work on this?

**Comment by TheLastProject** [comment]
Yes! Go ahead :) Tell me if you need any help :)

**Comment by roshaan005** [comment]
Sure! Could you please add the hacktober fest tag to this one since I am a participant 😊

**Comment by TheLastProject** [comment]
I don't think it's necessary for issues but if it makes you feel better, sure :) And welcome to Hacktoberfest :)

**Comment by roshaan005** [comment]
thank you so much!

**Comment by TheLastProject** [comment]
There is no About Us section on the website (yet). What information are you looking for?

**Comment by roshaan005** [comment]
Alright alright I thought you wanted to upgrade the section, no worries I ll start working on it from scratch (will look at the design you linked in the issue description)

**Comment by aditya3901** [comment]
Where can I get the data from? Version history, license info and all?

**Comment by TheLastProject** [comment]
Most info is in the already existing about screen.

Version history -> Show current value and open the browser to https://catima.app/changelog/ when clicking it
Credits -> See current about screen
Donate -> https://github.com/sponsors/TheLastProject
Help translate this app -> https://hosted.weblate.org/engage/catima/
License -> GNU GPL 3+, link to https://github.com/TheLastProject/Catima/blob/master/LICENSE
Source repository -> link to https://github.com/TheLastProject/Catima/
FAQ -> Doesn't exist at the moment, so skip that
Privacy policy -> https://catima.app/privacy-policy/

@roshaan005 was planning to work on this already though. @roshaan005 are you still interested in working on this, or can I give this issue to @aditya3901?

**Comment by roshaan005** [comment]
Due to some personal issues I can not work on this immediately, my apologies. You can assign it to someone else. I am really sorry for the delay

**Comment by TheLastProject** [comment]
It's fine, thanks for the quick response! :) I'll give @aditya3901 a chance to try this then :)

**Comment by aditya3901** [comment]
![Screenshot_20211002-235501_Catima Debug](https://user-images.githubusercontent.com/79566784/135727846-c07a5ba3-20ef-40c0-b122-dfa515f798fa.jpg)

Any changes that I should make? Or is it alright?

**Comment by TheLastProject** [comment]
Looks pretty great! If you make a Pull Request I can do a more in-depth review :)

**Comment by aditya3901** [comment]
I've made a pr. But can't see it under the pull requests tab. Kindly tell
me if you've received it or not.

**Comment by TheLastProject** [comment]
Yup I see it here: https://github.com/TheLastProject/Catima/pull/440

I'll take a look at it soon, kinda busy right now :)
