### ISSUE TITLE
Sort by bookmarked cards

### ISSUE THREAD

**Issue by Kajal13081** [TheLastProject/Catima#432]
Sort by bookmarks will be a good feature for catima users. Users can easily go through their bookmarks/ important cards without scrolling much. 
@TheLastProject Can you review this issue?

**Comment by TheLastProject** [comment]
Starred cards are already always on top, no matter what sorting method you use. So I'm not completely sure what you mean with this issue?

**Comment by Kajal13081** [comment]
> Starred cards are already always on top, no matter what sorting method you use. So I'm not completely sure what you mean with this issue?

Okay so in this case I am thinking to make a dedicated page for bookmarks with proper tags, collections, search function for saved cards only, user can manage the bookmarked card easily.
It really sucks if user have saved a lot of cards and didn't able to find what he needs at that time.

**Comment by TheLastProject** [comment]
I still don't really understand how it would make it faster to find the card you need.

If you want to search through all your starred cards, just go to the "All" group and search there because the starred cards will be on top?
![image](https://user-images.githubusercontent.com/1885159/135598417-59c6c0af-c62a-480f-87e7-6cbb0ff9700c.png)

If you only want to search through your starred cards of a certain group, go to that group and then click search?

**Comment by Kajal13081** [comment]
> I still don't really understand how it would make it faster to find the card you need.
> 
> If you want to search through all your starred cards, just go to the "All" group and search there because the starred cards will be on top? ![image](https://user-images.githubusercontent.com/1885159/135598417-59c6c0af-c62a-480f-87e7-6cbb0ff9700c.png)
> 
> If you only want to search through your starred cards of a certain group, go to that group and then click search?

Yes you are right. We already have what we want. So we can close this issue.

**Comment by Kajal13081** [comment]
Okay I got it. We already have everything for bookmark.
I would like to research more on this topic. If found some valid features will let you know.

**Comment by TheLastProject** [comment]
Sure, feel free to create another issue if you feel you're missing a feature :)
