### ISSUE TITLE
Group By Currency

### ISSUE THREAD

**Issue by rohanbabbar04** [TheLastProject/Catima#437]
Currently, there is no option to display all the cards based on a specific currency.
Like If a user selects a Dollar sign all the cards that have the currency dollar should be displayed.

**Comment by TheLastProject** [comment]
I want to avoid adding features for the sake of adding features, so could you please explain why this would be helpful for people? In what situation would it be useful to only show cards with $ currency?

**Comment by rohanbabbar04** [comment]
No, I was just giving an example like there should be an option to choose a currency and the cards related to that currency only should be displayed

**Comment by TheLastProject** [comment]
But why? Why would it be useful to be able to filter this way? What real life problem does it solve?

**Comment by rohanbabbar04** [comment]
Perhaps not an urgent requirement 
So I will just close the issue
