### ISSUE TITLE
StartActivityForResult Deprecated

### ISSUE THREAD

**Issue by rohanbabbar04** [TheLastProject/Catima#443]
The StartActivityForResult has been deprecated and should be replaced with registerForActivityResult which does away with request codes.

**Comment by Sanket-777** [comment]
can i work on this issue

**Comment by TheLastProject** [comment]
This would indeed be a good improvement.

Because @rohanbabbar04 identified this issue, I'll give them a chance to claim it first. If they don't want to do it it'll be yours @Sanket-777.

**Comment by rohanbabbar04** [comment]
I would like to work on it @TheLastProject

**Comment by TheLastProject** [comment]
Go ahead @rohanbabbar04 :)

**Comment by TacoTheDank** [comment]
I have experience fixing this deprecation, so I'd like to be able to review the PR when it is made.

**Comment by TheLastProject** [comment]
This was fixed in #612
