### ISSUE TITLE
UI and colour match

### ISSUE THREAD

**Issue by Kushagrasaxena-13** [TheLastProject/Catima#444]
I want to  contribute for the UI for this project for making it more attractive.

**Comment by TheLastProject** [comment]
What kind of UI changes are you planning to make?

**Comment by Kushagrasaxena-13** [comment]
To change colour pattern to make new eye sticking pattern

**Comment by TheLastProject** [comment]
Well, there are already 9 colour options available, so I'm not very convinced there is much space for improvement left there?

I mean, you're free to try anyway and see if you can convince me, but it may not be the best use of your time ^^"

**Comment by Kushagrasaxena-13** [comment]
![WhatsApp Image 2021-10-04 at 12 11 08 AM](https://user-images.githubusercontent.com/71897053/135767191-b80033a6-12be-4b65-9038-7a39eb40dd17.jpeg)

**Comment by Kushagrasaxena-13** [comment]
like this

**Comment by TheLastProject** [comment]
To be honest, I don't really like how that looks :(
