### ISSUE TITLE
Tapping on card icon in list should open it

### ISSUE THREAD

**Issue by tbertels** [TheLastProject/Catima#449]
When in the list, the most usual action is opening a card.
But currently, if we tap on a card icon instead of the text, we switch to selecting mode and the card just gets selected.

Given that long tap already switches to selecting mode and selects the card, opening on short tap seems more user friendly.
An entry could also be added to the dots menu to switch to selecting mode.

**Comment by TheLastProject** [comment]
Long press to select is indeed the default in Android. I agree making the icon open the card too makes more sense.

I don't think adding something to the dot menu is really necessary, just adds complexity for no clear reason.

**Comment by Biren-Nayak** [comment]
@tbertels hello i think i can solve this. Can you assign me to this issue?

**Comment by TheLastProject** [comment]
Given @tbertels was the first to identify this issue, I'm giving them a chance to claim this first if they want. If they don't want to take on this issue, it's yours @Biren-Nayak. Let's see what @tbertels says :)

**Comment by tbertels** [comment]
@Biren-Nayak is free to do it :)

**Comment by TheLastProject** [comment]
@Biren-Nayak All yours :)

**Comment by TheLastProject** [comment]
Fixed in f52423ed7059797cd175d9e196d61386a023b84b.
