### ISSUE TITLE
Change string about Stocard export since email seems the only way

### ISSUE THREAD

**Issue by tbertels** [TheLastProject/Catima#450]
The string currently says:

> Select your <i>***-sync.zip</i> export from Stocard to import.
**Or** get it by e-mailing support@stocardapp.com asking for an export of your data.

There doesn't seem to be a way to export data from the Stocard app. The email seems to be the only way.
So I suggest changing the string to 

> Get it by e-mailing support@stocardapp.com asking for an export of your data.

**Comment by TheLastProject** [comment]
The idea is that you e-mail stocard if you don't have the file yet. But yeah, removing the word "or" would give more clarity, I very much agree.

This change can be made directly on Weblate or, for those who are joining Hacktoberfest, see #402 for instructions on doing it the PR route.

**Comment by tbertels** [comment]
It seems that this "Or" is there for every import type.
Is it OK if I go ahead and remove it for each of them?

**Comment by TheLastProject** [comment]
Yeah, that would be perfect, thanks!

**Comment by tbertels** [comment]
It should be OK now.

**Comment by TheLastProject** [comment]
Yup, I see it changed in Weblate. Weblate will make a PR in the next 24 hours to merge the changes in the codebase.

Thanks! :)
