### ISSUE TITLE
[Feature Request] Balance Field

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#49]
<a href="https://github.com/trymeouteh"><img src="https://avatars3.githubusercontent.com/u/31172274?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [trymeouteh](https://github.com/trymeouteh)**
_Tuesday Sep 17, 2019 at 02:34 GMT_
_Originally opened as https://github.com/brarcher/loyalty-card-locker/issues/310_

----

Please add Balance field which will save the current balance of the gift card. This will have to be updated manually obviously but to have the field would make this more user friendly.

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Tuesday Sep 17, 2019 at 05:54 GMT_

----

Interesting. Is your use case to use this app to store gift card bar codes? Do you store the balance in the Notes field?

**Comment by TheLastProject** [comment]
<a href="https://github.com/trymeouteh"><img src="https://avatars3.githubusercontent.com/u/31172274?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [trymeouteh](https://github.com/trymeouteh)**
_Saturday Sep 28, 2019 at 02:08 GMT_

----

As of now yes I store the balances in the notes field but I would prefer to have a seperate field for balances.

I understand this app is mean't for club cards but it can be used for gift cards also.

**Comment by arshbeerSingh** [comment]
Can I work on this issue?

**Comment by TheLastProject** [comment]
It would probably be better to wait until I complete https://github.com/TheLastProject/Catima/pull/71 because I'm really close to having that done and it also edits the LoyaltyCardEditView so we may get merge conflicts then. I don't mind much, but it seems like creating more work than necessary to do it right now.

**Comment by TheLastProject** [comment]
Okay, this is probably implementable now, I think I'm done messing with the edit UI for now :)

**Comment by TheLastProject** [comment]
@arshbeerSingh Do you still want to do this? Otherwise I'd like to take this over.

**Comment by TheLastProject** [comment]
@arshbeerSingh I'll take this over probably this weekend if I don't hear from you on this issue.
