### ISSUE TITLE
Added option to keep the screen on

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#50]
<a href="https://github.com/franga2000"><img src="https://avatars3.githubusercontent.com/u/3891092?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [franga2000](https://github.com/franga2000)**
_Monday Oct 14, 2019 at 18:41 GMT_
_Originally opened as https://github.com/brarcher/loyalty-card-locker/pull/316_

----

Implements a setting that keeps the screen on and the app above the keyguard when displaying a barcode (as discussed in #287).

*(I noticed my previous PR was on an old version so this is the same but rebased to master)*

Signed-off-by: `Miha Frangež<miha.frangez@gmail.com>`

----

_**[franga2000](https://github.com/franga2000)** included the following code: https://github.com/brarcher/loyalty-card-locker/pull/316/commits_

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Saturday Oct 26, 2019 at 18:59 GMT_

----

Thanks for the change. 

Do you think it would be possible to test this change in Robolectric? There are tests for this activity in [LoyaltyCardViewActivityTest](https://github.com/brarcher/loyalty-card-locker/blob/master/app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java). There are a few tests which set settings. I've not tested window flags before to see if they are set, but I'm expecting it is possible. Could you look into adding a simple test?

**Comment by TheLastProject** [comment]
<a href="https://github.com/franga2000"><img src="https://avatars3.githubusercontent.com/u/3891092?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [franga2000](https://github.com/franga2000)**
_Monday Oct 28, 2019 at 11:20 GMT_

----

I doubt the kind of testing that Robolectric does would be of much use here. From what I've read about it, the best we could do is test whether the flags were actually set, but that would effectively just test whether the `Window.addFlags` method works.

A more interesting test would be whether the actual functionality of "screen doesn't time out" and "window stays above lock screen" works, but that would require something that runs on a full system. UIAutomator might be able to do it, but I'm not 100%.

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Friday Nov 01, 2019 at 04:53 GMT_

----

> I doubt the kind of testing that Robolectric does would be of much use here. From what I've read about it, the best we could do is test whether the flags were actually set, but that would effectively just test whether the Window.addFlags method works.

I think that a Robolectric test would ensure that the behavior of setting/clearing the setting has the expected behavior on the Window's flag. I'd count that as a success! The UI Automator would be more interesting, however the test setup I have for the project does not easily support running an emulator, so I'd like to avoid that path if possible.

Is it OK to add a Robolectric test for the setting, showing that the Window flags are set as expected?

**Comment by TheLastProject** [comment]
<a href="https://github.com/franga2000"><img src="https://avatars3.githubusercontent.com/u/3891092?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [franga2000](https://github.com/franga2000)**
_Friday Nov 01, 2019 at 18:04 GMT_

----

Ok. I'll add in the following week when I get back to by workstation.

**Comment by TheLastProject** [comment]
@franga2000 Are you still interested in working on this? Otherwise I'll see if I can integrate this into Catima myself.

**Comment by franga2000** [comment]
Wow, I completely forgot about this! :sweat_smile: I probably won't be able to work on this before the holidays, as I'm currently swimming in work, but if you don't mind waiting until then I can do it. I was actually using my version with this change for almost a year and it worked flawlessly, so I'm guessing it just needs some cleanup.

Same goes for #51

**Comment by TheLastProject** [comment]
Yeah, both features are pretty much good, just some unit tests and/or cleanups. You will have to make new PRs though and point them towards this repo (TheLastProject/Catima) I'm afraid, because Loyalty Card Keychain is no longer actively developed. But I'd still happily include these features.

**Comment by TheLastProject** [comment]
Well, we're almost three months further. So if I don't hear from you soon I will try to hook your old code into Catima myself unless you mind :)

**Comment by franga2000** [comment]
*I really need to start keeping a list of open PRs, because this is like the 5th one I've forgotten about in the last like 6 months :facepalm:...*

Sorry about the wait! I just rebased the changes, sent a PR and am currently fixing the half-finished test code I wrote for the original PR.

**Comment by TheLastProject** [comment]
Fixed in #149
