### ISSUE TITLE
Added ability to import a barcode from a local image

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#51]
<a href="https://github.com/franga2000"><img src="https://avatars3.githubusercontent.com/u/3891092?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [franga2000](https://github.com/franga2000)**
_Monday Oct 14, 2019 at 18:43 GMT_
_Originally opened as https://github.com/brarcher/loyalty-card-locker/pull/317_

----

Adds an "Import from image" button next to "Capture card" that does exactly what was described in #248 - allows the user to pick an image from their device that contains the barcode they want to add.

Signed-off-by: `Miha Frangež<miha.frangez@gmail.com>`

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/brarcher/loyalty-card-locker/317)

----

_**[franga2000](https://github.com/franga2000)** included the following code: https://github.com/brarcher/loyalty-card-locker/pull/317/commits_

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Sunday Oct 27, 2019 at 03:51 GMT_

----

Pretty cool!

Are you up for adding some Robolectric tests for this new feature? Much of the app has automated tests, which helps prevent breakage and regressions.

**Comment by TheLastProject** [comment]
<a href="https://github.com/franga2000"><img src="https://avatars3.githubusercontent.com/u/3891092?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [franga2000](https://github.com/franga2000)**
_Sunday Oct 27, 2019 at 07:12 GMT_

----

Sure. I'm not familiar with Robolectric, but I'll look into it.

**Comment by TheLastProject** [comment]
<a href="https://github.com/TheLastProject"><img src="https://avatars1.githubusercontent.com/u/1885159?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TheLastProject](https://github.com/TheLastProject)**
_Wednesday Nov 20, 2019 at 09:11 GMT_

----

I'm quite interested in this feature too. I don't normally do Android development but I'm willing to try to help if useful

**Comment by TheLastProject** [comment]
<a href="https://github.com/franga2000"><img src="https://avatars3.githubusercontent.com/u/3891092?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [franga2000](https://github.com/franga2000)**
_Wednesday Nov 20, 2019 at 10:06 GMT_

----

I got a bunch of uni work dumped on me so I haven't had any time to work on this. It looks like I'll be clear beginning of December, so you can expect this finished around then.

@TheLastProject thanks for the offer. I'm not sure GitHub would be very happy about mixing remote branches in one PR, but it's been a while since I've tried. If you can wait the two weeks, it's probably not worth the hassle of setting up Android Studio :sweat_smile:

**Comment by TheLastProject** [comment]
<a href="https://github.com/TheLastProject"><img src="https://avatars1.githubusercontent.com/u/1885159?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TheLastProject](https://github.com/TheLastProject)**
_Wednesday Nov 20, 2019 at 10:59 GMT_

----

Okay, I'll just wait then :)

**Comment by TheLastProject** [comment]
<a href="https://github.com/franga2000"><img src="https://avatars3.githubusercontent.com/u/3891092?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [franga2000](https://github.com/franga2000)**
_Thursday Nov 28, 2019 at 00:01 GMT_

----

I've been working on testing image importing by generating a barcode image, saving it and sending a fake pick intent response to the app. I have discovered, however, that the version of Robolectric used here doesn't actually implement image compression and is as such unable to save images to disk in a way that can read back.

It seems that the feature was only implemented in [v4.3.1](https://github.com/robolectric/robolectric/commit/b9e958a9dffe1f383e1d949754b9ee1ae80b931c). While the actual migration to v4 and up is not too difficult, it does, however, [require compiling on SDK 28](http://robolectric.org/migrating/#project-configuration) or higher.

Should I try to migrate the project to a newer version of Robolectric?

**Comment by TheLastProject** [comment]
<a href="https://github.com/TheLastProject"><img src="https://avatars1.githubusercontent.com/u/1885159?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TheLastProject](https://github.com/TheLastProject)**
_Thursday Nov 28, 2019 at 06:41 GMT_

----

I actually did a migration to Roboelectric 4 in my pull request in the hope it would fix things for me. It sadly didn't, but you may still want to take a look at https://github.com/brarcher/loyalty-card-locker/commit/0a9611ea675745431e000390ce17975f1a5c7bff to save yourself some time if you end up going that path

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Friday Nov 29, 2019 at 04:30 GMT_

----

>  While the actual migration to v4 and up is not too difficult, it does, however, require compiling on SDK 28 or higher.

The Play Store has a target SDK requirement which updates each year. As of Nov 1 this app will need to compile against SDK 28, else an update cannot be pushed to the Play Store.

https://support.google.com/googleplay/android-developer/answer/113469#targetsdk

If you would be so kind as to update it to 28 (or 29) that would be much appreciated.  I'm also fine with updating the version of Robolectric being used to the latest.

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Tuesday Dec 31, 2019 at 03:52 GMT_

----

> Should I try to migrate the project to a newer version of Robolectric?

To follow-up, https://github.com/brarcher/loyalty-card-locker/pull/334 recently was accepted which updates the SDK version compiled against to 29 and updates Robolectric to 4.0.2. 

If you are willing to upgrade the version of Robolectric used from 4.0.2 to 4.3.1 go for it. I've not looked into it; hopefully nothing that the existing tests use is deprecated and removed between those two versions. If you run into snags, let me know.

**Comment by TheLastProject** [comment]
@franga2000 Are you still interested in working on this? Otherwise I'll see if I can integrate this into Catima myself.

**Comment by mgohin** [comment]
I just got the app, and can't migrate from my old app (Fidme) to Catima quickly.
I don't own cards I added in Fidme anymore, so this feature would help me migrate 👍

**Comment by TheLastProject** [comment]
I'll take a look at doing the cleanups and writing the tests in #150 myself. I'll also try to support Fidme's export format in #168 (the GDPR is so amazing for requiring users to be allowed to export their data).

**Comment by TheLastProject** [comment]
Fixed in c93b7527ad89326554a52b40d8989d89fecd0ec3, going to give the translators a few days to translate stuff and then I'll push out a new release.
