### ISSUE TITLE
Photos section from card has a very low quality

### ISSUE THREAD

**Issue by ycodryn** [TheLastProject/Catima#532]
I`m trying to make my cov19 green card, the qr code is read correctly but the photos from the pdf are in a low quality when I`m trying to look at them from catima photos section. If I`m looking from gallery, photos are ok. I`m thinking that when you click on photo, should zoom/load in full quality not just a preview. I`m using latest version on a MI9 android  phone.

**Comment by TheLastProject** [comment]
The sizing was increased in cb5a98edad1df674581f11fc5e17daca96b7e800 so this should be fixed.
