### ISSUE TITLE
Code 93 support

### ISSUE THREAD

**Issue by franga2000** [TheLastProject/Catima#592]
Code 93 is *for whatever reason* used for membership cards by the National and University Library of Slovenia.

It is read correctly by Catima, but not displayed (it saves it as "no code"). Writing code 93 is supported by ZXing, so it looks to be just a matter of adding it to a list somewhere.

I'll gladly submit a PR adding support as soon as things slow down a bit at work, but I figured I'd open an issue to track this in the mean time. *Same goes for that still-open PR from almost a month ago at this point, sorry :sweat_smile:*

**Comment by TheLastProject** [comment]
That should be a relatively easy fix:

1. Add to CatimaBarcode.java
2. Add to BarcodeSelectorActivity.java
3. Add to barcode_selector_activity.xml

Kinda don't like how that's 3 parts, I should refactor the BarcodeSelectorActivity while I have some time and feel like it :P

**Comment by TheLastProject** [comment]
Since I merged #595 this should now be no more work than adding it to CatimaBarcode.java, but some double-checking would be in order

**Comment by Altonss** [comment]
The support for Code 39 barcodes has been added, and should be available in the next telease! So I think this issue can be closed for now. (Feel free to reopen it if any bug is detected)

**Comment by TheLastProject** [comment]
Oh, you're right, I forgot this issue.

Fixed in #659.
