### ISSUE TITLE
Train ticket is not scanned correctly (TER sncf hauts de france)

### ISSUE THREAD

**Issue by Altonss** [TheLastProject/Catima#615]
I just wanted to scan a train ticket from ter hauts de france (local train from SNCF), but the qr-code format is not recognised.
Is this normal as the format my be proprietary?
Here an example of this kind of qr code:
![image](https://user-images.githubusercontent.com/66519591/143582345-5fddd673-db86-4171-b3df-d18b207ffa1f.png)
(https://cdn.ter.sncf.com/medias/PDF/bretagne/Achat-application_tcm55-176071_tcm55-177382.pdf)

**Comment by TheLastProject** [comment]
Your example scans fine for me (it's just a standard Aztec code, just very very big).

What is exactly going wrong? Could you maybe do a screen recording?

**Comment by Altonss** [comment]
When I tried to scan a similar ticket, it recognised it just as a bar code containing an 8 digit id.

**Comment by TheLastProject** [comment]
Do you have enough light? Most of the time when people report such issues their camera has trouble focusing because the environment is too dark.

**Comment by Altonss** [comment]
Ok now the feedback (i don't know why it didn't work):
- I am now able to scan the example code (it was not an issue with the darkness, as I was scanning my screen, which was bright)
- The initial ticket with which I encountered the problem finally worked, when I stayed long enough scanning the code. But there is an issue here, because in some positions it detects a bar code!

**Comment by TheLastProject** [comment]
>But there is an issue here, because in some positions it detects a bar code!

Yeah, it can happen in some rare cases. There is sadly nothing I can do about that as far as I know. However, I will look into maybe changing the layout of the edit screen again so you can at least see it immediately if the scan went bad.
