### ISSUE TITLE
Groups list display issues

### ISSUE THREAD

**Issue by matsievskiysv** [TheLastProject/Catima#623]
Some group items are missing, some group items are duplicated in the group list.
Group items order changes on fling gesture.

https://user-images.githubusercontent.com/26824900/143785829-a23d2ee1-6e0e-4a3f-a7b9-f516e4ac789c.mp4

Notice not first two and last two items are duplicated and change order from time to time.
In this list two items are missing.

---
Version 2.10.0 from F-Droid

**Comment by TheLastProject** [comment]
Just curious, do you know if this was broken before 2.10.0 or not? I never had enough groups to scroll so I never noticed this bug, but I'll fix it.

**Comment by TheLastProject** [comment]
Nevermind my question, this bug has clearly been there for quite some time. I find this a very major bug, so I pushed out a release more quickly then normally. Catima 2.11.0 with the fix for this will probably be available on F-Droid in a few days.
