### ISSUE TITLE
Bug report: sometimes, no letter is displayed on the "preview icon"

### ISSUE THREAD

**Issue by Altonss** [TheLastProject/Catima#630]
Normal behavior:
![image](https://user-images.githubusercontent.com/66519591/143881430-95cf7e76-c97d-47c3-ba71-ff8ff17a720b.png)

Bug appearing after some "unknown" manipulations (some clue of the manipulation after the screenshot):
![image](https://user-images.githubusercontent.com/66519591/143881351-fcd21c1e-a6e0-4db7-a1f7-71474b3479a1.png)
 
EDIT how to reproduce:
- Enter the selection mode and select card.
- Then undo the selection and go out of the mode
- Some card don't have the letter in their icon anymore

Maybe the origin of the issue:
When selection an item, the validation hook covers the letter, which isn't displayed anymore. Maybe the bug is related to this :)

System information:
- Android 5.0.1
- Device: Samsung Galaxy Core Prime

**Comment by TheLastProject** [comment]
Good old RecyclerView...

Android has a component called RecyclerView that re-uses elements. I use it a lot because it severely improves performance, but if you make any mistake you can get really weird issues. I must have introduced some state bug again, sadly.

**Comment by TheLastProject** [comment]
The easiest way to consistently reproduce this is as follows:

1. Make sure you have more cards than fit on your screen
2. Select all card, scroll down as you select
3. Click the X to unselect everything
4. Scroll back up

The top cards now lack their image (it affects both the letters and other image)

**Comment by TheLastProject** [comment]
The LoyaltyCardAnimator did something that broke the icon display sometimes. Given Android already has a bit of animation from long-pressing a button, I figured to just delete it because it makes the code simpler and there is still some pretty animation anyway.
