### ISSUE TITLE
Make the star in the element overview list smaller?

### ISSUE THREAD

**Issue by Altonss** [TheLastProject/Catima#631]
When viewing the overview list and the stars, I see that the stars (favorite) are really big and a lot bigger than other interface elements like search icon, three dot menu... Also the star when editing each element is a lot smaller and correctly scaled to all other interface elements. Should we just take this size instead of the current bigger one?
So I was just thinking, if would be a good idea to reduce the size a little bit to have a more coherent look ?

Element list:
![image](https://user-images.githubusercontent.com/66519591/143883848-77aae89f-2ff8-4a12-a045-a8e220070367.png)

Element:
![image](https://user-images.githubusercontent.com/66519591/143883927-325d88fa-00dc-40e7-9222-229fc196b5f0.png)

**Comment by TheLastProject** [comment]
I'm closing this as I like how the UI currently looks and I think making the star smaller (especially with the new star style) may make it harder to read again.
