### ISSUE TITLE
Improve "Add Loyalty Card" > "Enter Card" > "Select Barcode" screen

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#64]
<a href="https://github.com/vertigo220"><img src="https://avatars2.githubusercontent.com/u/12024557?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vertigo220](https://github.com/vertigo220)**
_Thursday Aug 27, 2020 at 14:54 GMT_
_Originally opened as https://github.com/brarcher/loyalty-card-locker/issues/372_

----

When I first started using this yesterday, it took me a while to figure out how to choose different barcodes. Due to the size of my screen, I saw exactly one barcode and its name (AZTEC) and thought that was it, not realizing I had to scroll to see the others. I kept trying to tap the barcode and the name, thinking it would open a pop-up to select a different one. This could be made easier to understand for new users by doing one of two things (or both):

1) Change the text from "Enter the card ID then select the image..." to something like "Enter the card ID then scroll and select the image..."

2) Add a scroll bar, and make it stand out, to make it clear there's more below.

I realize this is a pretty minor thing, and most people will figure it out right away or fairly quickly, but I can imagine some people will struggle with it and possibly give up on the app because of it, which would be a shame.

**Comment by comradekingu** [comment]
>Enter the card ID, and either pick its barcode type below, or &#8220;This card has no barcode&#8221;

This is short and sweet. It took me a while to boil it down to this. I think this might improve matters further:

Show the barcodes by default right away to have less visual shifting.

Sort the barcodes side to side in a 2x3 grid.

**Comment by TheLastProject** [comment]
I feel there isn't really much space to use a grid and still make the differences clear, so I've done the following:

1. Set a default "hint" in the card ID field.
2. If a barcode cannot be generated for the value entered by the user, generate one for a known acceptable value. This "fallback" barcode is marked in code as being a fallback image and will be shown more grey and a message pops up when trying to select it.

I've attached a video of how it looks now:

https://user-images.githubusercontent.com/1885159/113620015-07fa4f80-965a-11eb-9105-882a0a60a0de.mp4

I think this would be the best possible way to fix this? (As always, I welcome suggestions for the exact phrasing of the "you can't select this" toast)

**Comment by TheLastProject** [comment]
I'll consider this solved in 4e043edb64b8eb8ce4969567266e85006de13848 unless you still have any complaints on this.
