### ISSUE TITLE
Crash when sharing a card

### ISSUE THREAD

**Issue by Altonss** [TheLastProject/Catima#646]
When trying to share a card from the card edit menu or from the cards selection menu, Catima crashes.

System information:
- Android 5.0.1
- Device: Samsung Galaxy Core Prime

**Comment by TheLastProject** [comment]
Thank you for the report, fixed in 6a91d5905039eb2e657e2bd3ecb1c6f82e11414a.

I think this is a regression from listening to spotBugs :(
