### ISSUE TITLE
Long-press to add card to group

### ISSUE THREAD

**Issue by comradekingu** [TheLastProject/Catima#649]
Only short-pressing groups to assign them to groups works,
I would expect long-pressing to work, and I don't think anything bad would happen(?).

**Comment by TheLastProject** [comment]
We probably just only bound the short-press handler in Android in the ManageGroupActivity. So just need to bind the long-press handler too. Should be a 5 minute fix if I'm right.

**Comment by Altonss** [comment]
I don't understand the issue, what is this bug really about?

**Comment by TheLastProject** [comment]
Groups -> Edit

Short press toggles selection
Long press does nothing

**Comment by Altonss** [comment]
Ah ok. So to fix this like in the main screen we should allow long and short press to toggle selection?

**Comment by TheLastProject** [comment]
Exactly :)

**Comment by Altonss** [comment]
I think I have the fix:
![image](https://user-images.githubusercontent.com/66519591/145453320-247b3bce-9c93-4d68-b9d9-d5c00643cd6b.png)
I will test it and then make a PR :)
