### ISSUE TITLE
Ability to edit card directly from card list to avoid brightness

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#65]
<a href="https://github.com/vertigo220"><img src="https://avatars2.githubusercontent.com/u/12024557?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vertigo220](https://github.com/vertigo220)**
_Thursday Aug 27, 2020 at 15:02 GMT_
_Originally opened as https://github.com/brarcher/loyalty-card-locker/issues/373_

----

First, having it automatically maximize brightness when viewing a card is great, and I'm surprised other apps haven't done it as well. The only issue I have with it, and it is very minor and low-priority since it's not something that would be a regular occurrence, but in order to edit a card, you have to open the card then select the edit icon. This means you have to be blasted by the bright light in the process, which isn't very comfortable, especially at night. If a way to edit cards directly from the list was added, whether by adding it to the long-click menu and/or by tapping the icon, then it could skip directly to the edit screen without showing the card and cranking the brightness in the meantime. Another option would be to possibly have an edit icon/switch on the main screen that could be turned on to switch to an edit mode, during which tapping on a card would open its edit screen, and turning it back off would return the app to its normal behavior of viewing the card when tapped.

**Comment by TheLastProject** [comment]
<a href="https://github.com/TheLastProject"><img src="https://avatars1.githubusercontent.com/u/1885159?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TheLastProject](https://github.com/TheLastProject)**
_Thursday Aug 27, 2020 at 15:48 GMT_

----

Adding this to the long-press menu feels very sensible to me. I believe the app returns to the last screen upon finishing editing but would need to double check this to make sure it doesn't instead bring you to the card after editing completes regardless

**Comment by TheLastProject** [comment]
<a href="https://github.com/vertigo220"><img src="https://avatars2.githubusercontent.com/u/12024557?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vertigo220](https://github.com/vertigo220)**
_Thursday Aug 27, 2020 at 22:50 GMT_

----

That's a good point. Wouldn't want to skip the bright screen when starting an edit only to end up on it when finishing. If that was the case, there would have to be a flag to specify whether the edit screen was accessed via the list vs the view screen.

**Comment by TheLastProject** [comment]
@arshbeerSingh You can if you want, but I want to get rid of the long-press menu on entries that currently shows "Copy ID to clipboard" and "Share" in favor of a [Contextual action bar](https://material.io/components/app-bars-top#contextual-action-bar) so we can also fix #14 and in the future have a nice way to put multiple cards in or out of a group at once. So if you work on this issue, please don't just add to the long press menu but replace it with a Contextual action bar because otherwise your work will be wasted when we switch to the contextual action bar.

**Comment by arshbeerSingh** [comment]
@TheLastProject can you please assign this issue to me?
