### ISSUE TITLE
Mention translation platform in "About"

### ISSUE THREAD

**Issue by comradekingu** [TheLastProject/Catima#652]
All other entries have
"on GitHub" or "on Google Play", but the one for the translation has nothing.
Should be
"on Hosted Weblate" I think.

**Comment by TheLastProject** [comment]
The idea was to show the percentage of how translated it is in the chosen language (see #467) but may as well just write "on Weblate" there.

**Comment by comradekingu** [comment]
That sounds like external requests, or possibly outdated data.
Both of which are solved with a user-initated click over to the always updated overview on Hosted Weblate.

If the user hasn't noticed missing or erroneous translations, no damage done.
If the user has noticed missing or erroneous translations, as much is clear.

I continually challenge percentage-wise completion as something meaningful, but it does IMO belong in package repo programs.

**Comment by Altonss** [comment]
Your right, I don't think the app should make any request to the internet. Just the link that is already implemented seems enough to me :)

**Comment by comradekingu** [comment]
Isn't that what we are keeping in mind.
>Contribute to the translation
**on Hosted Weblate**

explains what needs explaining to those not in the know.(?)

**Comment by Altonss** [comment]
> explains what needs explaining to those not in the know.(?)

Yes that's a good step! But I what I mean is that for 90% percent of the users that aren't in the too technical stuff hosted weblate means nothing to them ^^ But as you proposed it is perfect :)

**Comment by TheLastProject** [comment]
Fixed in #656.
