### ISSUE TITLE
[Wishlist] Add support to credit cards and NFC payment

### ISSUE THREAD

**Issue by airon90** [TheLastProject/Catima#668]
I'd like to use NFC payment with a (near) FOSS app. I know that credit cards are managed by banks so APIs are not open source so I know it is difficult to implement this request.

Info about NFC payments with [Mastercard](https://developer.mastercard.com/product/mobile-payments-sdk) and [Visa](https://developer.visa.com/capabilities/vts/docs).

**Comment by TheLastProject** [comment]
NFC is generally not possible (see #166) and I have no interest in adding a proprietary SDK to add Mastercard or Visa support.
