### ISSUE TITLE
When no system language selected, add new card crashes

### ISSUE THREAD

**Issue by Altonss** [TheLastProject/Catima#674]
When having not the system language selected, the app crashes when trying to add a new card (either by scanning it or entering it manually)

System information:
- Android 5.0.1
- Device: Samsung Galaxy Core Prime
- Catima 2.11.2 from F-Droid

**Comment by TheLastProject** [comment]
I can't reproduce this, might be another Android 5 specific bug. I will try to check in an emulator later

**Comment by Kethen** [comment]
Can't reproduce this with English/Deutsch as system language, while android studio/avd manager/google only provides android 5.0.2 for api level 21

nonetheless @Altonss what is your system language?

**Comment by Altonss** [comment]
I have french as system language. When changing the language in Catima to English or German I get this bug :/

**Comment by Kethen** [comment]
managed to reproduce that, looking into that now thanks @Altonss

**Comment by Altonss** [comment]
> managed to reproduce that, looking into that now thanks @Altonss

Is it due to french? :laughing:

**Comment by Kethen** [comment]
@Altonss it's language code and currency symbol resolution
it expects something like `de_DE` but after setting a language in Catima `de` or `fr` is used and it throws an exception
fixing it now...

**Comment by TheLastProject** [comment]
Fixed in #679
