### ISSUE TITLE
Sorry for the spam

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#68]
Hey everyone,

I'm making this issue and pinning it for about a week to explain what happened just now.

I'm Sylvia, I go by TheLastProject on GitHub. I love the Loyalty Card Keychain app by @brarcher and wanted to continue development on it after the original developer no longer had time to work on it. We communicated and decided forking was the only possible way to continue, so a non-hostile fork was made. That is this repository.

As I didn't want old issues to go ignored, I wanted to copy them over to this repository to keep track of them. GitHub's own issue mover cannot be used between repositories of different owners, so I could not use this method. Sadly, the copier script I found apparently pinged everyone, causing a lot of emails to be received by many people.

I apologize for this spam, I wasn't aware the script would cause these GitHub notification emails to be sent. If I would have known, I would not have used this specific tool.

-- Sylvia

**Comment by Efreak** [comment]
Suggestion for next time: GitHub makes it possible to transfer an entire repository (including issues, pulls, uploaded release binaries, etc) to another account. Consider if it's worthwhile to transfer the repo, give the original owner a fork (if they're interested; I wasn't when I did this) or access to your repo.

**Comment by TheLastProject** [comment]
Thanks for the suggestion. I'll make sure to suggest that next time I want to fork a project the main developer no longer has time to work on.
