### ISSUE TITLE
Issues introduced by merge of #675

### ISSUE THREAD

**Issue by Altonss** [TheLastProject/Catima#681]
Issue related to #675.
Here a screenshot of a before after on my android 5.0.2:
Before
![Screenshot_2021-12-13-23-23-57](https://user-images.githubusercontent.com/66519591/145898760-cbc52348-a90c-43e0-afa4-1eed08ed0b1e.png)

After
![Screenshot_2021-12-13-23-24-40](https://user-images.githubusercontent.com/66519591/145898764-024bf7e7-ac09-4137-bbc1-7dc9fe0cb54d.png)

Issues: the star is pixelated and the corners of the cards have changed. Is this intentional?

**Comment by Altonss** [comment]
Found another issue: when selecting a card, it becomes black instead of having it's color.

**Comment by TheLastProject** [comment]
> Found another issue: when selecting a card, it becomes black instead of having it's color.

I kinda think that's better actually, because it was possible to get colours where you couldn't see the red checkmark clearly.

**Comment by Altonss** [comment]
> I kinda think that's better actually, because it was possible to get colours where you couldn't see the red checkmark clearly.

I cannot reproduce it with the last stable release. It's a specific issue related to group widget, card widget and the app launch icon. Something is working great and it may also include the implementation of the card widget (the widget in general). I will try to look at this issue. What needs to be done: **When we click on a shortcut, it should open it whatever has been opened before**

**Comment by TheLastProject** [comment]
Turned it into a new issue (#706) to clean the issue tracker.
