### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [TheLastProject/Catima#690]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 19  warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on Catima (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure). 

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve Catima's security, and the quality of the reports of static analysis tools.
(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by TheLastProject** [comment]
I would be very surprised if Catima had any security vulnerabilities, especially given it can't connect to the Internet, but feel free to email a link to catima.g9ex3@hackerchick.me and I'll take a look if there is anything so dangerous it needs to be kept private until fixed, otherwise the rest (if relevant) should just be GitHub issues.

**Comment by TheLastProject** [comment]
From my email discussions from @misterAnderson90 none of the issues reported so far really had to do with Catima itself, only libraries.

Most found "possible issues" I couldn't make any meaningful statement about. The worst possible issue I could figure out was maybe, in some cases, password protection on exported .zip exports being easier to brute-force than expected.

I have asked @misterAnderson90 to report the issues to the relevant libraries directly, if any updates of used libraries come out I will be sure to apply them.

Closing this issue for now for the following reasons:
1. Nothing seems high-severity
2. None of the issues are directly in Catima
3. None of the issues can be worked around by Catima
4. If updates of used libraries are released, they will be applied.

Feel free to reopen if you have anything to add :)
