### ISSUE TITLE
Star icon should be light in main view on dark theme

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#72]
Very minor little thing:

![image](https://user-images.githubusercontent.com/1885159/97114159-19285300-16ef-11eb-8e18-10ef4b3c76a1.png)

**Comment by arshbeerSingh** [comment]
Can I work on this issue?

**Comment by TheLastProject** [comment]
Sure! :) Is this related to Hacktoberfest? Just asking so I can add a `hacktoberfest-accepted'` label so your pull request counts for that.

**Comment by TheLastProject** [comment]
It works correctly in the LoyaltyCardViewActivity by the way, so you can probably copy some logic from there. Although if you end up copying it I'd of course rather you move it to a place both the LoyaltyCardViewActivity and the MainActivity can use it :)

**Comment by arshbeerSingh** [comment]
@TheLastProject It is not related to Hacktoberfest. I am taking part in that event and I have already fulfilled its requirements.
I was looking to fix some easy beginner issues as I am new to contributing to open-source projects :-)
Also, can you please assign this issue to me?

**Comment by TheLastProject** [comment]
Done :)

**Comment by arshbeerSingh** [comment]
Hi @TheLastProject , I tried to fix this issue in two ways:
1. changing the star icon to a light colour in dark mode
2. changing the star icon to golden shiny colour (same colour for both light and dark themes)
I think that the second option is better as it represents the favourite icon in a better way and at the same time reduces code complexity. But, I would also like your opinion (Please refer to the attached screenshots)
![white](https://user-images.githubusercontent.com/50064542/97207124-df9b2a80-1776-11eb-8ac5-81a01f43a34b.PNG)
![golden_1](https://user-images.githubusercontent.com/50064542/97207196-f6418180-1776-11eb-8273-a473a1098a9e.PNG)
![golden_2](https://user-images.githubusercontent.com/50064542/97207197-f6da1800-1776-11eb-8acc-d455f67c3607.PNG)



 on what option do you think should be finalized as you are the project owner.

**Comment by TheLastProject** [comment]
I personally prefer option 1, as it is more consistent with other UI elements and icons and fits the Android design guidelines. I definitely do see value in your suggestion though and I do really appreciate your thinking along like this. Still, option 1 please :)

**Comment by arshbeerSingh** [comment]
Sure, I do agree with your preference and would submit a pull request soon with option 1 implemented. :+1:

**Comment by TheLastProject** [comment]
Awesome, thank you :)

**Comment by TheLastProject** [comment]
Fixed in #75.
