### ISSUE TITLE
Small picture (logo) per card 

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#8]
<a href="https://github.com/x-jokay"><img src="https://avatars0.githubusercontent.com/u/18613935?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [x-jokay](https://github.com/x-jokay)**
_Saturday Jan 28, 2017 at 16:26 GMT_
_Originally opened as https://github.com/brarcher/loyalty-card-locker/issues/86_

----

It would be great to be able to set a small picture per card on the overview.

Or even having an overview with the logo and name of the card only:
https://c.mobilegeeks.de/wp-content/uploads/2013/02/stocard-04.jpg

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Saturday Jan 28, 2017 at 17:13 GMT_

----

Before creating this application I took a look at Stocard and a few others and how they worked. My concern with packaging the logos in the app is a legal one ([discussion here](https://www.quora.com/Can-I-use-another-companys-logo-on-my-website)). It is not clear to me if I would need to get permission from each company in writing prior to packaging their logo into the application and using it. Stocard's model appears to be based on partnerships with retailers. Although I do not know for sure, I suspect Stocard has the permission of the 1800 companies (as reported on Google Play) whose logo it uses.

It is unfortunately more complicated than all of that, however. This application is free (as in speech and beer) because of the license I have selected (GPLv3). To provide the assets with the same freedom if a logo from another company were to be included the company would need to give permission not only to me but to anyone who would fork this project, not knowing what they may do with it.

In the end, I am glad to provide an application that I (and hopefully others) find useful. I do not want to expose myself to legal trouble, nor be able to provide the application with the level of freedom and flexibility I expect. 

Sadly, although your feature request would be really nice to have, I must decline it. Hopefully the reason is understood.

**Comment by TheLastProject** [comment]
<a href="https://github.com/x-jokay"><img src="https://avatars0.githubusercontent.com/u/18613935?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [x-jokay](https://github.com/x-jokay)**
_Saturday Jan 28, 2017 at 17:23 GMT_

----

The idea was not to package the logos directly into the application but to provide the possibility to set a picture per card.

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Saturday Jan 28, 2017 at 17:56 GMT_

----

Oh, that sounds do-able.

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Saturday Jan 28, 2017 at 17:57 GMT_

----

How would that work, in your mind? Would the user take a picture with the camera of a logo? Would they import a photo? Something else?

**Comment by TheLastProject** [comment]
<a href="https://github.com/x-jokay"><img src="https://avatars0.githubusercontent.com/u/18613935?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [x-jokay](https://github.com/x-jokay)**
_Saturday Jan 28, 2017 at 18:05 GMT_

----

For stocard I had taken some picture from a google image search and cropped it before setting it in the app.

You may link to an existing picture from the user's gallery or better import / copy it to some sub-dir of the loyality-card-locker data dir?

**Comment by TheLastProject** [comment]
<a href="https://github.com/x-jokay"><img src="https://avatars0.githubusercontent.com/u/18613935?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [x-jokay](https://github.com/x-jokay)**
_Saturday Jan 28, 2017 at 18:06 GMT_

----

Or do directly a base64 encode of the picture.

**Comment by TheLastProject** [comment]
<a href="https://github.com/ni720"><img src="https://avatars1.githubusercontent.com/u/5901728?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ni720](https://github.com/ni720)**
_Tuesday Feb 21, 2017 at 13:01 GMT_

----

That would significantly raise the acceptance in some shops for this app. As soon as an employee sees the logo of his company he is more likely to accept scanning the loyalty card from an app. Some shops however have a strict no-app-policy.

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Wednesday Feb 22, 2017 at 02:55 GMT_

----

> Some shops however have a strict no-app-policy

Really? I've not heard of that before. Interesting.

I am for the idea of having a user selectable logo displayed with the summary on the main page and with the barcode. What is holding back the idea is a nice layout design for when there is and is not a logo present. I'm not the best that that, and am hoping that someone with an idea may contribute a suggestion.

**Comment by TheLastProject** [comment]
<a href="https://github.com/x-jokay"><img src="https://avatars0.githubusercontent.com/u/18613935?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [x-jokay](https://github.com/x-jokay)**
_Wednesday Feb 22, 2017 at 05:07 GMT_

----

Why not using a default card icon as kind of placeholder if no picture was set?

**Comment by TheLastProject** [comment]
<a href="https://github.com/x-jokay"><img src="https://avatars0.githubusercontent.com/u/18613935?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [x-jokay](https://github.com/x-jokay)**
_Wednesday Feb 22, 2017 at 05:25 GMT_

----

![1_overview](https://cloud.githubusercontent.com/assets/18613935/23198401/9a141340-f8c7-11e6-92f6-962bf68b2aca.png)
![2_edit-nopic](https://cloud.githubusercontent.com/assets/18613935/23198403/9a45581a-f8c7-11e6-9dbd-aa9f23a9b86c.png)
![3_show-nopic](https://cloud.githubusercontent.com/assets/18613935/23198404/9a458d76-f8c7-11e6-8fca-e2345b605ba6.png)
![4_show-nopic-adv](https://cloud.githubusercontent.com/assets/18613935/23198405/9a46af08-f8c7-11e6-9df4-defb486b7d0b.png)
![5_edit-pic](https://cloud.githubusercontent.com/assets/18613935/23198406/9a47b240-f8c7-11e6-9122-d6acb10173dd.png)
![6_show-pic](https://cloud.githubusercontent.com/assets/18613935/23198407/9a4b0fda-f8c7-11e6-92ce-921851df3946.png)
![7_show-pic-menu](https://cloud.githubusercontent.com/assets/18613935/23198402/9a2ec79e-f8c7-11e6-8491-a9194de71f77.png)

**Comment by TheLastProject** [comment]
<a href="https://github.com/x-jokay"><img src="https://avatars0.githubusercontent.com/u/18613935?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [x-jokay](https://github.com/x-jokay)**
_Wednesday Feb 22, 2017 at 05:25 GMT_

----

Some samples without and with icon.

**Comment by TheLastProject** [comment]
<a href="https://github.com/x-jokay"><img src="https://avatars0.githubusercontent.com/u/18613935?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [x-jokay](https://github.com/x-jokay)**
_Wednesday Feb 22, 2017 at 06:08 GMT_

----

I'm not sure if it's really necessary to have the barcode displayed on the main page?

**Comment by TheLastProject** [comment]
<a href="https://github.com/jimmyswimmy"><img src="https://avatars0.githubusercontent.com/u/1754151?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jimmyswimmy](https://github.com/jimmyswimmy)**
_Friday Apr 07, 2017 at 04:04 GMT_

----

This last set of pictures offers an interesting idea - it would be awesome to include pictures of the card.  I was shopping at Costco and the cashier wanted to see the card, but then scanned my phone... but he said if I'd had pictures he would have accepted that.  I'd be interested to try to implement this (know nothing about android programming but I'm a quick study) if x-jokay has all of those icons etc.  I hate front end work.

**Comment by TheLastProject** [comment]
<a href="https://github.com/x-jokay"><img src="https://avatars0.githubusercontent.com/u/18613935?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [x-jokay](https://github.com/x-jokay)**
_Friday Apr 07, 2017 at 05:20 GMT_

----

The screenshots were taken from the app stocard, I don't "own" those icons.

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Friday Apr 07, 2017 at 20:49 GMT_

----

If the issue is icons, I've used a number of icons from [The Noun Project](thenounproject.com) for other applications. @jimmyswimmy, if you are interested in taking this on and need some icons, maybe give that a look. The only thing which would need to be done is to ensure that the icons are release under a Creative Commons license and give credit in the [README](https://github.com/brarcher/loyalty-card-locker/blob/master/README.md) and in the [About dialog](https://github.com/brarcher/loyalty-card-locker/blob/master/app/src/main/java/protect/card_locker/MainActivity.java#L164). [Here](https://github.com/brarcher/loyalty-card-locker/blob/master/app/src/main/java/protect/card_locker/MainActivity.java#L164) is an example of adding references for image resources.

**Comment by TheLastProject** [comment]
<a href="https://github.com/ioangogo"><img src="https://avatars3.githubusercontent.com/u/7449028?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ioangogo](https://github.com/ioangogo)**
_Tuesday Jul 25, 2017 at 11:20 GMT_

----

Has any progress happened in this issue yet, I am tempted to work on this issue as I also feel like it would be useful in shops that might be a bit hesitant on scanning a barcode from this app

I'm currently thinking about how display it on the card page, I'll upload some scribbles at a later point as I am currently not near a laptop/desktop

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Tuesday Jul 25, 2017 at 11:44 GMT_

----

I've not made any progress on this. I encourage you to give it a shot!

**Comment by TheLastProject** [comment]
<a href="https://github.com/x-jokay"><img src="https://avatars0.githubusercontent.com/u/18613935?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [x-jokay](https://github.com/x-jokay)**
_Tuesday Jul 25, 2017 at 11:47 GMT_

----

Not as I'm aware of :)

Anyway, mobile payment solution providers start to integrate customer cards directly and will be used automatically during payment process.

We may continue to use this app for customer cards which are not yet supported.

**Comment by TheLastProject** [comment]
<a href="https://github.com/ioangogo"><img src="https://avatars3.githubusercontent.com/u/7449028?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ioangogo](https://github.com/ioangogo)**
_Thursday Jul 27, 2017 at 13:15 GMT_

----

Currently i have 3 ideas for the placement of the store logo, 2 i have mocked up in GIMP and the other is just having the logo over the barcode. I like it being by the store name, but that only works with stores that have a logo like the national trust, or the body-shop, most have their name in the logo so having it above the barcode may work but does not allow for low resolution images.

Mockups:

1
![left](https://user-images.githubusercontent.com/7449028/28671759-b7f07394-72d5-11e7-9a92-40c39edc5395.png)
2
![right](https://user-images.githubusercontent.com/7449028/28671760-b7f0d744-72d5-11e7-8ffa-01c35c93bc05.png)

**Comment by TheLastProject** [comment]
<a href="https://github.com/ioangogo"><img src="https://avatars3.githubusercontent.com/u/7449028?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ioangogo](https://github.com/ioangogo)**
_Thursday Jul 27, 2017 at 22:42 GMT_

----

@x-jokay yeah, android pay supports quite a few now, although I did find this useful when visiting a national trust property and my farther had forgotten his card

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Friday Jul 28, 2017 at 00:22 GMT_

----

> but that only works with stores that have a logo like the national trust

I would expect that if the store had or did not have the name in the logo it would still be recognizable to the end user, and may not require having the store name and logo both.

Could you create a mock-up with the logo above the barcode, to see what that is like? 

> but does not allow for low resolution images

Do you mean that if one were to use a low resolution image it would not look good, so for a good experience one would need to source higher resolution images?

**Comment by TheLastProject** [comment]
<a href="https://github.com/ioangogo"><img src="https://avatars3.githubusercontent.com/u/7449028?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ioangogo](https://github.com/ioangogo)**
_Friday Jul 28, 2017 at 00:45 GMT_

----

@brarcher on the resultion thing, yes I did mean that

I'll try to make a mock up of the logo above the barcode when I can.

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Friday Jul 28, 2017 at 02:14 GMT_

----

Thanks for taking this on, @ioangogo!

**Comment by TheLastProject** [comment]
<a href="https://github.com/ioangogo"><img src="https://avatars3.githubusercontent.com/u/7449028?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ioangogo](https://github.com/ioangogo)**
_Monday Jul 31, 2017 at 17:22 GMT_

----

Here is a mock up of it above the barcode

![screenshot 31 jul 2017 5-34-51 pm](https://user-images.githubusercontent.com/7449028/28789324-d30081d4-761c-11e7-8061-735e47cf561e.png)

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Monday Jul 31, 2017 at 17:35 GMT_

----

I like the full sized barcode more, what do you think?

Another thing that I am thinking is perhaps the order of the information could be better, to put the more relevant information closer to the top. For example:

![image](https://user-images.githubusercontent.com/5264535/28789685-7d7116ca-75f4-11e7-9e77-8b71a02d5ead.png)

Or, another option might be to omit the store name if there is an icon:

![image](https://user-images.githubusercontent.com/5264535/28789762-bd9e735a-75f4-11e7-8631-e15e0352715b.png)

Do you have an opinion on the order of the presented data? Perhaps there is a better idea.

**Comment by TheLastProject** [comment]
<a href="https://github.com/ioangogo"><img src="https://avatars3.githubusercontent.com/u/7449028?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ioangogo](https://github.com/ioangogo)**
_Monday Jul 31, 2017 at 18:40 GMT_

----

I personaly prefer the current set up, It just kind of flows with the large images at the bottom and the small text at the top

**Comment by TheLastProject** [comment]
<a href="https://github.com/ioangogo"><img src="https://avatars3.githubusercontent.com/u/7449028?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ioangogo](https://github.com/ioangogo)**
_Wednesday Aug 02, 2017 at 14:22 GMT_

----

> Or do directly a base64 encode of the picture.

@x-jokay the app uses a sqlite database so it may be possible to use the SQLITE BLOB data type, but to keep the CSV exporting simple I might use your suggestion

**Comment by TheLastProject** [comment]
<a href="https://github.com/matthijskooijman"><img src="https://avatars3.githubusercontent.com/u/194491?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [matthijskooijman](https://github.com/matthijskooijman)**
_Friday Sep 15, 2017 at 16:48 GMT_

----

Just to double-check: Is this issue about just adding a logo, or are photographs of the card itself also considered? It has been mentioned in the comments, but I'm not sure if they're also considered (I do think images of the card, front and back, really add something. Using the front side of the card as the "logo" in the overview of cards works really well in [mobile pocket](https://play.google.com/store/apps/details?id=at.bluesource.mobilepocket&hl=en) which I was using before). If it helps, I'm happy to create a separate issue for that, though I suspect these could be tied together, also in terms of implementation.

**Comment by TheLastProject** [comment]
<a href="https://github.com/x-jokay"><img src="https://avatars0.githubusercontent.com/u/18613935?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [x-jokay](https://github.com/x-jokay)**
_Sunday Sep 24, 2017 at 19:34 GMT_

----

It was about adding a logo to the card (manually from the gallery) :)

I think a separate issue for this will be a good idea.

This issue can then be linked if it really makes sense for the implementation.

**Comment by TheLastProject** [comment]
<a href="https://github.com/ioangogo"><img src="https://avatars3.githubusercontent.com/u/7449028?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ioangogo](https://github.com/ioangogo)**
_Monday Dec 11, 2017 at 01:37 GMT_

----

Sadly due to workload related reasons I will probably not be able to do this now, I hope someone else picks this up. I had written some code, but it was mostly updating the database, sadly the laptop it was on died and I haddent committed it to my fork

**Comment by x-jokay** [comment]
@TheLastProject umad?

**Comment by TheLastProject** [comment]
No clue what you're talking about, just copying over issues because I'm continuing this project (see the README of brarcher/loyalty-card-locker). I guess this import tool pinged everyone then. That's quite unfortunate, wasn't my intention to cause any type of spam. I'll report that to the import tool. Sadly GitHub doesn't offer any native support for copying issues yet I still want to keep track of what issues I have fixed in my fork so... yeah...

**Comment by x-jokay** [comment]
> I guess this import tool pinged everyone then.

You guessed right 🙄

**Comment by OmlineEditor** [comment]
I support adding a square image in place of the current icon as an initial letter. The user will choose ready-made pictures from the gallery. No need to take photos and photo cropping and editing functions. there will be no photos in your application, the user adds them himself.

**Comment by redseasix** [comment]
> [<img alt="" width="48" height="48" src="https://avatars0.githubusercontent.com/u/18613935?v=4">](https://github.com/x-jokay) **Kommentar von [x-jokay](https://github.com/x-jokay)**
> _ Mittwoch, 22. Februar 2017 um 05:25 GMT_
> 
> ![1. Übersicht](https://cloud.githubusercontent.com/assets/18613935/23198401/9a141340-f8c7-11e6-92f6-962bf68b2aca.png)
> ![2_edit-nopic](https://cloud.githubusercontent.com/assets/18613935/23198403/9a45581a-f8c7-11e6-9dbd-aa9f23a9b86c.png)
> ![3_show-nopic](https://cloud.githubusercontent.com/assets/18613935/23198404/9a458d76-f8c7-11e6-8fca-e2345b605ba6.png)
> ![4_show-nopic-adv](https://cloud.githubusercontent.com/assets/18613935/23198405/9a46af08-f8c7-11e6-9df4-defb486b7d0b.png)
> ![5_edit-pic](https://cloud.githubusercontent.com/assets/18613935/23198406/9a47b240-f8c7-11e6-9122-d6acb10173dd.png)
> ![6_show-pic](https://cloud.githubusercontent.com/assets/18613935/23198407/9a4b0fda-f8c7-11e6-92ce-921851df3946.png)
> ![7_show-pic-menu](https://cloud.githubusercontent.com/assets/18613935/23198402/9a2ec79e-f8c7-11e6-8491-a9194de71f77.png)

I think your idea is good and practicable. Legally, that shouldn't be a problem because the user decides for himself what it wants to use as an image.
advantage it is simple and if the first picture is also used as a logo you do not need a logo database

**Comment by jokay** [comment]
@redseasix yes, but it seems very difficult to provide a simple file chooser and set a locally stored image, so the discussion goes on ^^

**Comment by TheLastProject** [comment]
Well, it's more that there are a lot of things to make and I want to make the things well. Given the knowledge I gained dealing with images by implementing front and back card image for the next release (which took a few attempts to get right) this should become easier to implement properly soon.

**Comment by TheLastProject** [comment]
Sorry this has been taking so long! It's finally probably ready (after some further testing) after @leaumar figured out why the tests were failing (I should never have used `setID()` in Android, it did not do what 4 months ago me expected it to do).

Thanks everyone for your patience and @leaumar for helping fix this :)

**Comment by jokay** [comment]
Good news, after using [Wear Codes](https://play.google.com/store/apps/details?id=org.codechimp.qrwear) on my wear OS smartwatch ^^

Any plans on making your app work on wear OS too?

**Comment by TheLastProject** [comment]
See #25 for that. I don't have any WearOS devices myself though so that will probably need to be community-contributed.

**Comment by jokay** [comment]
I don't think it will be this different than on an Android smartphone *(beside the screen size, which surely need app optimizations)*.
