### ISSUE TITLE
Fastlane directories

### ISSUE THREAD

**Issue by IzzySoft** [TheLastProject/Catima#88]
May I suggest to use "simple language" directory names instead of "regionalized"? Currently, e.g. `de-DE` would be skipped for Austrians not having that explicitly defined (they usually set `de-AT,de`). Similarly, French speaking people all over the workd do not necessarily live in France. So both would get `en-US` (fallback), though something much better fitting is available – just because it's not found.

So with the only exception of `en-US` (which for some reason I'll never understand is required as fallback, instead of `en`), could you please use the "base language"? Currently that would mean: `de`, `en-US`, (optionally `en` as symlink to `en-US`,) `fr`. Not sure about `nb_NO`, so maybe leave that as-is.

Thanks!

**Comment by IzzySoft** [comment]
PS: `nb_NO` should be `nb-NO` (no underscore but a simple dash). As it's now, it won't be found at all as it's invalid.

**Comment by TheLastProject** [comment]
I changed them because `fastlane supply` would fail to upload them to Google Play:

```
$ cd ~/Projects/Catima/fastlane/metadata/android
$ ls -1
de
en
fr
$ cd ~/Projects/Catima
$ fastlane supply --version-code 42
[19:13:32]: Preparing to upload for language 'de'...                                                                                                                       
                                                                                                                                                                           
[...]
                                                                                                                                                                           
/usr/local/share/gems/gems/google-api-client-0.38.0/lib/google/apis/core/http_command.rb:227:in `check_status': badRequest: The requested language is not currently supported: de. (Google::Apis::ClientError)

[...]

[19:14:51]: Preparing to upload for language 'en'...                                                                                                                       

/usr/local/share/gems/gems/google-api-client-0.38.0/lib/google/apis/core/http_command.rb:227:in `check_status': badRequest: The requested language is not currently supported: en. (Google::Apis::ClientError)

[...]

[19:16:39]: Preparing to upload for language 'fr'...                                                                                                                       

[...]

/usr/local/share/gems/gems/google-api-client-0.38.0/lib/google/apis/core/http_command.rb:227:in `check_status': badRequest: The requested language is not currently supported: fr. (Google::Apis::ClientError)
```

So, unless you know a way to work around this, I'm afraid. I tried adding symlinks, but that also breaks `fastlane supply` and will trigger the errors above again. And `nb_NO` does work but so does `nb-NO` so I renamed it for consistency.

So I'm closing this as, well, it doesn't seem like I can fix this without breaking uploading to Google Play. But I'll reopen it if you want me to try anything else.

**Comment by IzzySoft** [comment]
Ugh, Google's stupid. Not an error on Fastlane's end but on Google's. OK, I'm adding the symlinks at my end – but that won't solve it for F-Droid.org (not sure how it's handled there).

Thanks for fixing `nb`! Might well be that Google accepts underscores there, not sure if F-Droid does. Fdroidserver seems to simply copy it, but whether the client understands it I cannot tell. Looking at the metadata we have at our end, except for `en-US` most language directories are 2-chars only. Exceptions are if language variants are available *in addition* to the "base language" – e.g. `pt` is there and also `pt-BR` (Brasilia).

:man_shrugging: What can we do… :man_shrugging: We won't convince Google (probably not even reach a real person to try)…

**Comment by TheLastProject** [comment]
Maybe you could submit a `generate-fastlane-language-symlinks-for-fdroid.sh` script that creates these symlinks and add it to the f-droid prebuilt? I can't think of a better way to solve this sadly. If there is anything specific that breaks F-Droid you can always tell me and I can see if I can fix it without breaking Google.

**Comment by IzzySoft** [comment]
I've asked on IRC. It's not really my area of proficience, but gathering metadata for the index doesn't take place at build time (it happens on index generation). But as those structures are inside your own repo, it might work in prebuild indeed – provided the build directory is contained afterwards. I guess it is, but I'm not sure.

I don't know who's active on IRC now (I've suggested your approach as it sounds good to me). If the script would break something, you can always see that in the logs – e.g. if your app doesn't turn up with the next index after having tagged a new release, you can check. Find some helpful URLs [here](https://gitlab.com/snippets/1896503).

Maybe the F-Droid-Client-logic even handles it in its current state (I've included that with my question there). The logic in my website does not (and implementing it would get too complex: when do I have to add what exception, and when rather not, etc).

**Comment by eighthave** [comment]
The Google Play locale names should work fine in F-Droid.  I recommend using the Google Play locale names if you plan on also syncing to Google Play.  If you are only interested in F-Droid, you can use any valid locale names.

**Comment by IzzySoft** [comment]
OK, just got answer on IRC: F-Droid Android client seems to be able to deduce "de" from "de-DE". Not sure about the website, though (my web front-end does not).

Suggestion was to have both variants in Fastlane and ignore those errors (or open an issue with Fastlane to demote them to "info" level, so the pipeline still completes "with no errors"). I don't like the idea of duplicating content and would suggest symlinks instead (still waiting for the answer on the prebuild script). Another variant would be temporarily renaming those directories before running `fastlane supply`, if that would be an option for you. Last variant is leaving it as-is and saying "sorry affected users, Google messed it up – say thanks to THEM". For the current ones, I've set up symlinks on my end for now.

**Comment by IzzySoft** [comment]
Hi Sylvia, here comes another very good approach just suggested on IRC by smichel:

* leave your current Fastlane structure as-is (xx-XX) for use with `fastlane supply`
* have a copy/symlink (not checked, but symlink should work) for "simple languages" (de, en etc) in one of the other supported locations (eg `metadata/`, `/src/<buildFlavor>/fastlane/metadata/android/`)

No "prebuild script" needed then, fdroidserver would merge them accordingly. More details in a longer discussion [here](https://gitlab.com/fdroid/fdroidserver/-/issues/829).

Though going by the details Hans just gave, this won't be needed for the F-Droid client. Not sure about the F-Droid website (remains to be seen; so once your app is there, please check if this would still make sense). Just my repo browser would still be affected (though for now I have symlinks in place on my end to work around that, so no urgency).
